In [2]:
import sqlite3
import time
import pandas as pd

In [3]:
conn = sqlite3.connect('nba_stats.db')

query = 'SELECT * FROM basic_stats'
basic_stats_df = pd.read_sql_query(query, conn)

conn.close()

pd.set_option('display.max_columns', None)
basic_stats_df.head()

,slug,season_end_year,name,positions,age,team,games_played,games_started,minutes_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,attempted_three_point_field_goals,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points
0,abdulma02,2001,Mahmoud Abdul-Rauf,POINT GUARD,31,VANCOUVER GRIZZLIES,41,0,486,120,246,4,14,22,29,5,20,76,9,1,26,50,266
1,abdulta01,2001,Tariq Abdul-Wahad,SHOOTING GUARD,26,DENVER NUGGETS,29,12,420,43,111,4,10,21,36,14,45,22,14,13,34,54,111
2,abdursh01,2001,Shareef Abdur-Rahim,SMALL FORWARD,24,VANCOUVER GRIZZLIES,81,81,3241,604,1280,12,64,443,531,175,560,250,90,77,231,238,1663
3,alexaco01,2001,Cory Alexander,POINT GUARD,27,ORLANDO MAGIC,26,0,227,18,56,4,16,12,18,0,25,36,16,0,25,29,52
4,alexaco02,2001,Courtney Alexander,POINT GUARD,23,DALLAS MAVERICKS/WASHINGTON WIZARDS,65,24,1382,239,573,17,46,123,150,42,101,62,45,5,75,139,618

In [4]:
missing_data = basic_stats_df.isna().any(axis=None)
print(missing_data)

False

In [5]:
conn = sqlite3.connect('nba_stats.db')

query = 'SELECT * FROM advanced_stats'
advanced_stats_df = pd.read_sql_query(query, conn)

conn.close()

advanced_stats_df.head()

,slug,season_end_year,name,positions,age,team,games_played,minutes_played,player_efficiency_rating,true_shooting_percentage,three_point_attempt_rate,free_throw_attempt_rate,offensive_rebound_percentage,defensive_rebound_percentage,total_rebound_percentage,assist_percentage,steal_percentage,block_percentage,turnover_percentage,usage_percentage,offensive_win_shares,defensive_win_shares,win_shares,win_shares_per_48_minutes,offensive_box_plus_minus,defensive_box_plus_minus,box_plus_minus,value_over_replacement_player
0,finlemi01,2001,Michael Finley,SMALL FORWARD,27,DALLAS MAVERICKS,82,3443,18.2,0.521,0.169,0.209,3.6,10.0,6.9,18.3,1.8,0.7,10.1,24.9,5.6,2.9,8.5,0.119,2.4,-0.5,1.9,3.4
1,walkean02,2001,Antoine Walker,POWER FORWARD,24,BOSTON CELTICS,81,3396,18.9,0.505,0.351,0.202,5.0,20.4,12.3,26.8,2.1,1.1,13.8,29.1,2.7,3.8,6.6,0.093,3.5,-0.5,3.0,4.3
2,jamisan01,2001,Antawn Jamison,SMALL FORWARD,24,GOLDEN STATE WARRIORS,82,3394,19.0,0.499,0.113,0.295,8.1,14.8,11.2,9.5,1.7,0.6,8.9,27.9,5.4,1.3,6.7,0.094,2.8,-2.0,0.8,2.3
3,masonan01,2001,Anthony Mason,POWER FORWARD,34,MIAMI HEAT,80,3254,17.4,0.555,0.000,0.497,6.2,21.9,14.1,14.2,1.4,0.6,13.3,20.0,6.0,5.6,11.6,0.171,0.8,1.1,1.9,3.2
4,paytoga01,2001,Gary Payton,POINT GUARD,32,SEATTLE SUPERSONICS,79,3244,22.1,0.522,0.171,0.223,2.6,10.1,6.4,36.6,2.1,0.6,10.7,27.2,9.1,1.7,10.8,0.160,4.7,-0.7,4.0,4.9

In [6]:
conn = sqlite3.connect('nba_stats.db')

query = 'SELECT * FROM derived_stats'
derived_stats_df = pd.read_sql_query(query, conn)

conn.close()

derived_stats_df.head()

,slug,season_end_year,name,positions,age,team,games_played,games_started,minutes_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,attempted_three_point_field_goals,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points,player_efficiency_rating,true_shooting_percentage,three_point_attempt_rate,free_throw_attempt_rate,offensive_rebound_percentage,defensive_rebound_percentage,total_rebound_percentage,assist_percentage,steal_percentage,block_percentage,turnover_percentage,usage_percentage,offensive_win_shares,defensive_win_shares,win_shares,win_shares_per_48_minutes,offensive_box_plus_minus,defensive_box_plus_minus,box_plus_minus,value_over_replacement_player,fg_percentage,three_point_percentage,ft_percentage,effective_fg_percentage,points_per_36,assists_per_36,offensive_rebounds_per_36,defensive_rebounds_per_36,steals_per_36,blocks_per_36,turnovers_per_36,personal_fouls_per_36,total_rebounds_per_36,points_per_game,assists_per_game,total_rebounds_per_game,steals_per_game,blocks_per_game,turnovers_per_game,minutes_per_game,assist_to_turnover_ratio,stocks_per_game,win_shares_per_game
0,abdulma02,2001,Mahmoud Abdul-Rauf,POINT GUARD,31,VANCOUVER GRIZZLIES,41,0,486,120,246,4,14,22,29,5,20,76,9,1,26,50,266,16.7,0.514,0.057,0.118,1.2,4.7,2.9,32.7,1.0,0.1,9.1,26.8,0.7,0.0,0.7,0.070,1.1,-2.1,-1.0,0.1,0.487805,0.285714,0.758621,0.495935,19.703704,5.629630,0.370370,1.481481,0.666667,0.074074,1.925926,3.703704,1.851852,6.487805,1.853659,0.609756,0.219512,0.024390,0.634146,11.853659,2.923077,0.243902,0.017073
1,abdulta01,2001,Tariq Abdul-Wahad,SHOOTING GUARD,26,DENVER NUGGETS,29,12,420,43,111,4,10,21,36,14,45,22,14,13,34,54,111,5.8,0.438,0.090,0.324,3.6,11.8,7.6,8.1,1.7,2.1,21.1,17.1,-0.7,0.3,-0.4,-0.049,-5.6,-0.3,-5.8,-0.4,0.387387,0.400000,0.583333,0.405405,9.514286,1.885714,1.200000,3.857143,1.200000,1.114286,2.914286,4.628571,5.057143,3.827586,0.758621,2.034483,0.482759,0.448276,1.172414,14.482759,0.647059,0.931034,-0.013793
2,abdursh01,2001,Shareef Abdur-Rahim,SMALL FORWARD,24,VANCOUVER GRIZZLIES,81,81,3241,604,1280,12,64,443,531,175,560,250,90,77,231,238,1663,19.1,0.549,0.050,0.415,6.2,19.6,13.0,14.3,1.5,1.6,13.2,24.6,5.6,2.9,8.5,0.126,1.7,0.1,1.8,3.1,0.471875,0.187500,0.834275,0.476562,18.472077,2.776921,1.943844,6.220302,0.999691,0.855292,2.565875,2.643629,8.164147,20.530864,3.086420,9.074074,1.111111,0.950617,2.851852,40.012346,1.082251,2.061728,0.104938
3,alexaco01,2001,Cory Alexander,POINT GUARD,27,ORLANDO MAGIC,26,0,227,18,56,4,16,12,18,0,25,36,16,0,25,29,52,6.3,0.407,0.286,0.321,0.0,12.5,6.1,23.5,3.6,0.0,28.1,17.3,-0.5,0.3,-0.1,-0.031,-7.2,1.2,-6.0,-0.2,0.321429,0.250000,0.666667,0.357143,8.246696,5.709251,0.000000,3.964758,2.537445,0.000000,3.964758,4.599119,3.964758,2.000000,1.384615,0.961538,0.615385,0.000000,0.961538,8.730769,1.440000,0.615385,-0.003846
4,alexaco02,2001,Courtney Alexander,POINT GUARD,23,DALLAS MAVERICKS/WASHINGTON WIZARDS,65,24,1382,239,573,17,46,123,150,42,101,62,45,5,75,139,618,11.6,0.484,0.080,0.262,3.5,8.4,5.9,8.0,1.7,0.3,10.5,23.2,0.3,0.5,0.8,0.027,-2.4,-1.9,-4.3,-0.8,0.417103,0.369565,0.820000,0.431937,16.098408,1.615051,1.094067,2.630970,1.172214,0.130246,1.953690,3.620839,3.725036,9.507692,0.953846,2.200000,0.692308,0.076923,1.153846,21.261538,0.826667,0.769231,0.012308

In [7]:
derived_stats_df = derived_stats_df[derived_stats_df['slug'] == 'abdursh01']
derived_stats_df

,slug,season_end_year,name,positions,age,team,games_played,games_started,minutes_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,attempted_three_point_field_goals,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points,player_efficiency_rating,true_shooting_percentage,three_point_attempt_rate,free_throw_attempt_rate,offensive_rebound_percentage,defensive_rebound_percentage,total_rebound_percentage,assist_percentage,steal_percentage,block_percentage,turnover_percentage,usage_percentage,offensive_win_shares,defensive_win_shares,win_shares,win_shares_per_48_minutes,offensive_box_plus_minus,defensive_box_plus_minus,box_plus_minus,value_over_replacement_player,fg_percentage,three_point_percentage,ft_percentage,effective_fg_percentage,points_per_36,assists_per_36,offensive_rebounds_per_36,defensive_rebounds_per_36,steals_per_36,blocks_per_36,turnovers_per_36,personal_fouls_per_36,total_rebounds_per_36,points_per_game,assists_per_game,total_rebounds_per_game,steals_per_game,blocks_per_game,turnovers_per_game,minutes_per_game,assist_to_turnover_ratio,stocks_per_game,win_shares_per_game
2,abdursh01,2001,Shareef Abdur-Rahim,SMALL FORWARD,24,VANCOUVER GRIZZLIES,81,81,3241,604,1280,12,64,443,531,175,560,250,90,77,231,238,1663,19.1,0.549,0.050,0.415,6.2,19.6,13.0,14.3,1.5,1.6,13.2,24.6,5.6,2.9,8.5,0.126,1.7,0.1,1.8,3.1,0.471875,0.187500,0.834275,0.476562,18.472077,2.776921,1.943844,6.220302,0.999691,0.855292,2.565875,2.643629,8.164147,20.530864,3.086420,9.074074,1.111111,0.950617,2.851852,40.012346,1.082251,2.061728,0.104938
442,abdursh01,2002,Shareef Abdur-Rahim,POWER FORWARD,25,ATLANTA HAWKS,77,77,2980,598,1297,21,70,419,523,198,498,239,98,81,250,214,1636,19.8,0.536,0.054,0.403,7.6,19.2,13.3,15.1,1.7,2.0,14.1,27.0,4.1,3.1,7.2,0.116,1.9,-0.2,1.7,2.8,0.461064,0.300000,0.801147,0.469160,19.763758,2.887248,2.391946,6.016107,1.183893,0.978523,3.020134,2.585235,8.408054,21.246753,3.103896,9.038961,1.272727,1.051948,3.246753,38.701299,0.956000,2.324675,0.093506
882,abdursh01,2003,Shareef Abdur-Rahim,POWER FORWARD,26,ATLANTA HAWKS,81,81,3087,566,1183,21,60,455,541,175,502,242,87,38,212,240,1608,19.9,0.566,0.051,0.457,6.7,17.8,12.5,14.7,1.5,0.9,13.0,24.2,7.4,2.3,9.7,0.151,2.3,-0.7,1.6,2.8,0.478445,0.350000,0.841035,0.487320,18.752187,2.822157,2.040816,5.854227,1.014577,0.443149,2.472303,2.798834,7.895044,19.851852,2.987654,8.358025,1.074074,0.469136,2.617284,38.111111,1.141509,1.543210,0.119753
1309,abdursh01,2004,Shareef Abdur-Rahim,POWER FORWARD,27,ATLANTA HAWKS/PORTLAND TRAIL BLAZERS,85,56,2684,501,1054,9,34,373,429,189,450,174,68,37,184,222,1384,19.9,0.557,0.032,0.407,8.2,19.0,13.6,12.3,1.4,1.0,12.9,24.4,6.1,2.0,8.1,0.145,2.3,-0.7,1.6,2.4,0.475332,0.264706,0.869464,0.479602,18.563338,2.333830,2.535022,6.035768,0.912072,0.496274,2.467958,2.977645,8.570790,16.282353,2.047059,7.517647,0.800000,0.435294,2.164706,31.576471,0.945652,1.235294,0.095294
1751,abdursh01,2005,Shareef Abdur-Rahim,POWER FORWARD,28,PORTLAND TRAIL BLAZERS,54,49,1867,337,670,15,39,220,254,123,269,111,49,26,117,150,909,18.7,0.581,0.058,0.379,7.9,16.0,12.1,10.7,1.4,1.0,13.0,22.1,3.9,1.5,5.4,0.139,1.6,-0.6,0.9,1.4,0.502985,0.384615,0.866142,0.514179,17.527584,2.140332,2.371719,5.186931,0.944831,0.501339,2.256026,2.892341,7.558650,16.833333,2.055556,7.259259,0.907407,0.481481,2.166667,34.574074,0.948718,1.388889,0.100000
2215,abdursh01,2006,Shareef Abdur-Rahim,POWER FORWARD,29,SACRAMENTO KINGS,72,30,1961,332,632,5,22,218,278,106,251,149,48,42,108,227,887,17.2,0.588,0.035,0.440,6.4,14.8,10.6,13.2,1.3,1.6,12.5,20.1,4.0,2.2,6.2,0.152,0.5,0.4,0.9,1.4,0.525316,0.227273,0.784173,0.529272,16.283529,2.735339,1.945946,4.607853,0.881183,0.771035,1.982662,4.167262,6.553799,12.319444,2.069444,4.958333,0.666667,0.583333,1.500000,27.236111,1.379630,1.250000,0.086111
2673,abdursh01,2007,Shareef Abdur-Rahim,CENTER,30,SACRAMENTO KINGS,80,45,2015,310,654,3,20,170,234,122,276,109,53,40,116,243,793,13.1,0.524,0.031,0.358,7.0,16.4,11.6,9.2,1.3,1.5,13.3,19.5,1.1,1.7,2.8,0.067,-2.0,-0.5,-2.5,-0.2,0.474006,0.150000,0.726496,0.476300,14.167742,1.947395,2.179653,4.931017,0.946898,0.714640,2.072457,4.341439,7.110670,9.912500,1.362500,4.975000,0.662500,0.500000,1.450000,25.187500,0.939655,1.162500,0.035000
3131,abdursh01,2008,Shareef Abdur-Rahim,POWER FORWARD,31,SACRAMENTO KINGS,6,0,51,3,14,0,0,4,4,6,4,4,1,0,1,9,10,5.5,0.317,0.000,0.286,14.2,9.1,11.6,11.1,1.0,0.0,6.0,14.7,0.0,0.0,0.0,-0.005,-4.4,-2.5,-6.9,-0.1,0.214286,NaN,1.000000,0.214286,7.058824,2.823529,4.235294,2.823529,0.705882,0.000000,0.705882,6.352941,7.058824,1.666667,0.666667,1.666667,0.166667,0.000000,0.166667,8.500000,4.000000,0.166667,0.000000

In [8]:
sar_advanced_stats_df = advanced_stats_df[advanced_stats_df['slug'] == 'abdursh01']
sar_advanced_stats_df

,slug,season_end_year,name,positions,age,team,games_played,minutes_played,player_efficiency_rating,true_shooting_percentage,three_point_attempt_rate,free_throw_attempt_rate,offensive_rebound_percentage,defensive_rebound_percentage,total_rebound_percentage,assist_percentage,steal_percentage,block_percentage,turnover_percentage,usage_percentage,offensive_win_shares,defensive_win_shares,win_shares,win_shares_per_48_minutes,offensive_box_plus_minus,defensive_box_plus_minus,box_plus_minus,value_over_replacement_player
5,abdursh01,2001,Shareef Abdur-Rahim,SMALL FORWARD,24,VANCOUVER GRIZZLIES,81,3241,19.1,0.549,0.050,0.415,6.2,19.6,13.0,14.3,1.5,1.6,13.2,24.6,5.6,2.9,8.5,0.126,1.7,0.1,1.8,3.1
465,abdursh01,2002,Shareef Abdur-Rahim,POWER FORWARD,25,ATLANTA HAWKS,77,2980,19.8,0.536,0.054,0.403,7.6,19.2,13.3,15.1,1.7,2.0,14.1,27.0,4.1,3.1,7.2,0.116,1.9,-0.2,1.7,2.8
898,abdursh01,2003,Shareef Abdur-Rahim,POWER FORWARD,26,ATLANTA HAWKS,81,3087,19.9,0.566,0.051,0.457,6.7,17.8,12.5,14.7,1.5,0.9,13.0,24.2,7.4,2.3,9.7,0.151,2.3,-0.7,1.6,2.8
1359,abdursh01,2004,Shareef Abdur-Rahim,POWER FORWARD,27,None,85,2684,19.9,0.557,0.032,0.407,8.2,19.0,13.6,12.3,1.4,1.0,12.9,24.4,6.1,2.0,8.1,0.145,2.3,-0.7,1.6,2.4
1878,abdursh01,2005,Shareef Abdur-Rahim,POWER FORWARD,28,PORTLAND TRAIL BLAZERS,54,1867,18.7,0.581,0.058,0.379,7.9,16.0,12.1,10.7,1.4,1.0,13.0,22.1,3.9,1.5,5.4,0.139,1.6,-0.6,0.9,1.4
2338,abdursh01,2006,Shareef Abdur-Rahim,POWER FORWARD,29,SACRAMENTO KINGS,72,1961,17.2,0.588,0.035,0.440,6.4,14.8,10.6,13.2,1.3,1.6,12.5,20.1,4.0,2.2,6.2,0.152,0.5,0.4,0.9,1.4
2797,abdursh01,2007,Shareef Abdur-Rahim,CENTER,30,SACRAMENTO KINGS,80,2015,13.1,0.524,0.031,0.358,7.0,16.4,11.6,9.2,1.3,1.5,13.3,19.5,1.1,1.7,2.8,0.067,-2.0,-0.5,-2.5,-0.2
3556,abdursh01,2008,Shareef Abdur-Rahim,POWER FORWARD,31,SACRAMENTO KINGS,6,51,5.5,0.317,0.000,0.286,14.2,9.1,11.6,11.1,1.0,0.0,6.0,14.7,0.0,0.0,0.0,-0.005,-4.4,-2.5,-6.9,-0.1

In [9]:
conn = sqlite3.connect('nba_stats.db')

query = 'SELECT * FROM per_100_stats'
per_100_stats_df = pd.read_sql_query(query, conn)

conn.close()

per_100_stats_df.head()

,season_end_year,player_id,player_name,nickname,team_id,team_abbreviation,age,gp,w,l,w_pct,per_100_min,per_100_fgm,per_100_fga,per_100_fg_pct,per_100_fg3m,per_100_fg3a,per_100_fg3_pct,per_100_ftm,per_100_fta,per_100_ft_pct,per_100_oreb,per_100_dreb,per_100_reb,per_100_ast,per_100_tov,per_100_stl,per_100_blk,per_100_blka,per_100_pf,per_100_pfd,per_100_pts,per_100_plus_minus,per_100_nba_fantasy_pts,dd2,td3,per_100_wnba_fantasy_pts,gp_rank,w_rank,l_rank,w_pct_rank,min_rank,fgm_rank,fga_rank,fg_pct_rank,fg3m_rank,fg3a_rank,fg3_pct_rank,ftm_rank,fta_rank,ft_pct_rank,oreb_rank,dreb_rank,reb_rank,ast_rank,tov_rank,stl_rank,blk_rank,blka_rank,pf_rank,pfd_rank,pts_rank,plus_minus_rank,nba_fantasy_pts_rank,dd2_rank,td3_rank,wnba_fantasy_pts_rank,team_count
0,2001,920,A.C. Green,A.C.,1610612748,MIA,37.0,82,50,32,0.610,53.1,5.4,12.2,0.444,0.0,0.2,0.000,3.0,4.2,0.712,4.0,7.7,11.8,1.5,1.7,1.1,0.3,1.1,4.5,0.0,13.8,3.9,32.7,3,0,29.9,2,38,163,130,33,310,345,171,295,295,295,248,242,259,115,128,123,376,401,326,328,204,273,58,328,90,356,126,26,367,1
1,2001,2062,A.J. Guyton,A.J.,1610612741,CHI,23.0,33,6,27,0.182,53.6,6.6,16.4,0.406,2.3,5.9,0.391,1.3,1.5,0.833,0.9,2.2,3.1,5.5,2.0,0.8,0.4,0.3,3.0,0.0,16.9,-12.4,30.3,0,0,30.1,334,381,231,419,21,202,186,293,51,59,62,390,409,71,367,429,427,117,368,392,286,417,403,112,227,408,388,224,26,365,1
2,2001,243,Aaron McKie,Aaron,1610612755,PHI,28.0,76,51,25,0.671,51.5,7.3,15.4,0.473,1.1,3.7,0.312,3.2,4.2,0.768,0.7,6.0,6.7,8.1,4.4,2.3,0.2,1.2,3.8,0.0,18.9,7.2,42.2,8,2,39.8,120,31,251,57,162,157,216,106,149,143,181,213,239,176,386,214,277,45,39,75,363,168,331,112,168,32,148,77,4,144,1
3,2001,1425,Aaron Williams,Aaron,1610612751,NJN,29.0,82,26,56,0.317,51.6,6.6,14.4,0.457,0.0,0.0,0.000,5.4,6.8,0.787,4.7,8.4,13.0,1.9,2.9,1.3,2.5,1.5,7.0,0.0,18.5,-8.4,45.6,12,0,41.1,2,223,12,358,157,210,263,141,295,353,295,61,70,146,76,99,89,329,220,287,51,97,89,112,185,364,94,53,26,118,1
4,2001,228,Adam Keefe,Adam,1610612744,GSW,31.0,67,14,53,0.209,50.5,3.8,9.5,0.403,0.1,0.2,0.333,2.3,3.8,0.619,5.4,7.1,12.5,2.2,2.4,1.7,1.2,1.2,6.1,0.0,10.1,-10.3,34.6,0,0,30.6,192,318,18,407,283,400,402,300,268,306,145,303,274,345,36,157,101,311,307,184,141,171,140,112,399,383,323,224,26,352,1

    season_end_year  true_shooting_percentage
0              2001                  0.488732
1              2002                  0.493030
2              2003                  0.483481
3              2004                  0.487244
4              2005                  0.502110
5              2006                  0.506201
6              2007                  0.510854
7              2008                  0.513111
8              2009                  0.520861
9              2010                  0.522520
10             2011                  0.513781
11             2012                  0.500220
12             2013                  0.504271
13             2014                  0.510535
14             2015                  0.509967
15             2016                  0.524590
16             2017                  0.525870
17             2018                  0.529009
18             2019                  0.530755
19             2020                  0.537871
20             2021                  0.544180
21             2022                  0.523787
22             2023                  0.560590
23             2024                  0.545093
24             2025                  0.545548
25             2026                  0.564235

In [ ]:
conn = sqlite3.connect('nba_stats.db')

query = '''
SELECT season_end_year,
    SUM(points) * 1.0 / (2.0 * (SUM(attempted_field_goals) + 0.44 * SUM(attempted_free_throws))) AS league_avg_ts_pct
FROM basic_stats
GROUP BY season_end_year
'''
league_avg_ts_df = pd.read_sql_query(query, conn)

conn.close()
league_avg_ts_df