In [2]:
import sqlite3
import time
import pandas as pd

In [3]:
conn = sqlite3.connect('nba_stats.db')

query = 'SELECT * FROM basic_stats'
basic_stats_df = pd.read_sql_query(query, conn)

conn.close()

pd.set_option('display.max_columns', None)
basic_stats_df.head()

,slug,season_end_year,name,positions,age,team,games_played,games_started,minutes_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,attempted_three_point_field_goals,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points
0,abdulma02,2001,Mahmoud Abdul-Rauf,POINT GUARD,31,VANCOUVER GRIZZLIES,41,0,486,120,246,4,14,22,29,5,20,76,9,1,26,50,266
1,abdulta01,2001,Tariq Abdul-Wahad,SHOOTING GUARD,26,DENVER NUGGETS,29,12,420,43,111,4,10,21,36,14,45,22,14,13,34,54,111
2,abdursh01,2001,Shareef Abdur-Rahim,SMALL FORWARD,24,VANCOUVER GRIZZLIES,81,81,3241,604,1280,12,64,443,531,175,560,250,90,77,231,238,1663
3,alexaco01,2001,Cory Alexander,POINT GUARD,27,ORLANDO MAGIC,26,0,227,18,56,4,16,12,18,0,25,36,16,0,25,29,52
4,alexaco02,2001,Courtney Alexander,POINT GUARD,23,DALLAS MAVERICKS/WASHINGTON WIZARDS,65,24,1382,239,573,17,46,123,150,42,101,62,45,5,75,139,618

In [4]:
missing_data = basic_stats_df.isna().any(axis=None)
print(missing_data)

False

In [5]:
conn = sqlite3.connect('nba_stats.db')

query = 'SELECT * FROM advanced_stats'
advanced_stats_df = pd.read_sql_query(query, conn)

conn.close()

advanced_stats_df.head()

,slug,season_end_year,name,positions,age,team,games_played,minutes_played,player_efficiency_rating,true_shooting_percentage,three_point_attempt_rate,free_throw_attempt_rate,offensive_rebound_percentage,defensive_rebound_percentage,total_rebound_percentage,assist_percentage,steal_percentage,block_percentage,turnover_percentage,usage_percentage,offensive_win_shares,defensive_win_shares,win_shares,win_shares_per_48_minutes,offensive_box_plus_minus,defensive_box_plus_minus,box_plus_minus,value_over_replacement_player
0,finlemi01,2001,Michael Finley,SMALL FORWARD,27,DALLAS MAVERICKS,82,3443,18.2,0.521,0.169,0.209,3.6,10.0,6.9,18.3,1.8,0.7,10.1,24.9,5.6,2.9,8.5,0.119,2.4,-0.5,1.9,3.4
1,walkean02,2001,Antoine Walker,POWER FORWARD,24,BOSTON CELTICS,81,3396,18.9,0.505,0.351,0.202,5.0,20.4,12.3,26.8,2.1,1.1,13.8,29.1,2.7,3.8,6.6,0.093,3.5,-0.5,3.0,4.3
2,jamisan01,2001,Antawn Jamison,SMALL FORWARD,24,GOLDEN STATE WARRIORS,82,3394,19.0,0.499,0.113,0.295,8.1,14.8,11.2,9.5,1.7,0.6,8.9,27.9,5.4,1.3,6.7,0.094,2.8,-2.0,0.8,2.3
3,masonan01,2001,Anthony Mason,POWER FORWARD,34,MIAMI HEAT,80,3254,17.4,0.555,0.000,0.497,6.2,21.9,14.1,14.2,1.4,0.6,13.3,20.0,6.0,5.6,11.6,0.171,0.8,1.1,1.9,3.2
4,paytoga01,2001,Gary Payton,POINT GUARD,32,SEATTLE SUPERSONICS,79,3244,22.1,0.522,0.171,0.223,2.6,10.1,6.4,36.6,2.1,0.6,10.7,27.2,9.1,1.7,10.8,0.160,4.7,-0.7,4.0,4.9

In [6]:
conn = sqlite3.connect('nba_stats.db')

query = 'SELECT * FROM derived_stats'
derived_stats_df = pd.read_sql_query(query, conn)

conn.close()

derived_stats_df.head()

,slug,season_end_year,name,positions,age,team,games_played,games_started,minutes_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,attempted_three_point_field_goals,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points,player_efficiency_rating,true_shooting_percentage,three_point_attempt_rate,free_throw_attempt_rate,offensive_rebound_percentage,defensive_rebound_percentage,total_rebound_percentage,assist_percentage,steal_percentage,block_percentage,turnover_percentage,usage_percentage,offensive_win_shares,defensive_win_shares,win_shares,win_shares_per_48_minutes,offensive_box_plus_minus,defensive_box_plus_minus,box_plus_minus,value_over_replacement_player,fg_percentage,three_point_percentage,ft_percentage,effective_fg_percentage,points_per_36,assists_per_36,offensive_rebounds_per_36,defensive_rebounds_per_36,steals_per_36,blocks_per_36,turnovers_per_36,personal_fouls_per_36,total_rebounds_per_36,points_per_game,assists_per_game,total_rebounds_per_game,steals_per_game,blocks_per_game,turnovers_per_game,minutes_per_game,assist_to_turnover_ratio,stocks_per_game,win_shares_per_game
0,abdulma02,2001,Mahmoud Abdul-Rauf,POINT GUARD,31,VANCOUVER GRIZZLIES,41,0,486,120,246,4,14,22,29,5,20,76,9,1,26,50,266,16.7,0.514,0.057,0.118,1.2,4.7,2.9,32.7,1.0,0.1,9.1,26.8,0.7,0.0,0.7,0.070,1.1,-2.1,-1.0,0.1,0.487805,0.285714,0.758621,0.495935,19.703704,5.629630,0.370370,1.481481,0.666667,0.074074,1.925926,3.703704,1.851852,6.487805,1.853659,0.609756,0.219512,0.024390,0.634146,11.853659,2.923077,0.243902,0.017073
1,abdulta01,2001,Tariq Abdul-Wahad,SHOOTING GUARD,26,DENVER NUGGETS,29,12,420,43,111,4,10,21,36,14,45,22,14,13,34,54,111,5.8,0.438,0.090,0.324,3.6,11.8,7.6,8.1,1.7,2.1,21.1,17.1,-0.7,0.3,-0.4,-0.049,-5.6,-0.3,-5.8,-0.4,0.387387,0.400000,0.583333,0.405405,9.514286,1.885714,1.200000,3.857143,1.200000,1.114286,2.914286,4.628571,5.057143,3.827586,0.758621,2.034483,0.482759,0.448276,1.172414,14.482759,0.647059,0.931034,-0.013793
2,abdursh01,2001,Shareef Abdur-Rahim,SMALL FORWARD,24,VANCOUVER GRIZZLIES,81,81,3241,604,1280,12,64,443,531,175,560,250,90,77,231,238,1663,19.1,0.549,0.050,0.415,6.2,19.6,13.0,14.3,1.5,1.6,13.2,24.6,5.6,2.9,8.5,0.126,1.7,0.1,1.8,3.1,0.471875,0.187500,0.834275,0.476562,18.472077,2.776921,1.943844,6.220302,0.999691,0.855292,2.565875,2.643629,8.164147,20.530864,3.086420,9.074074,1.111111,0.950617,2.851852,40.012346,1.082251,2.061728,0.104938
3,alexaco01,2001,Cory Alexander,POINT GUARD,27,ORLANDO MAGIC,26,0,227,18,56,4,16,12,18,0,25,36,16,0,25,29,52,6.3,0.407,0.286,0.321,0.0,12.5,6.1,23.5,3.6,0.0,28.1,17.3,-0.5,0.3,-0.1,-0.031,-7.2,1.2,-6.0,-0.2,0.321429,0.250000,0.666667,0.357143,8.246696,5.709251,0.000000,3.964758,2.537445,0.000000,3.964758,4.599119,3.964758,2.000000,1.384615,0.961538,0.615385,0.000000,0.961538,8.730769,1.440000,0.615385,-0.003846
4,alexaco02,2001,Courtney Alexander,POINT GUARD,23,DALLAS MAVERICKS/WASHINGTON WIZARDS,65,24,1382,239,573,17,46,123,150,42,101,62,45,5,75,139,618,11.6,0.484,0.080,0.262,3.5,8.4,5.9,8.0,1.7,0.3,10.5,23.2,0.3,0.5,0.8,0.027,-2.4,-1.9,-4.3,-0.8,0.417103,0.369565,0.820000,0.431937,16.098408,1.615051,1.094067,2.630970,1.172214,0.130246,1.953690,3.620839,3.725036,9.507692,0.953846,2.200000,0.692308,0.076923,1.153846,21.261538,0.826667,0.769231,0.012308

In [7]:
derived_stats_df = derived_stats_df[derived_stats_df['slug'] == 'abdursh01']
derived_stats_df

,slug,season_end_year,name,positions,age,team,games_played,games_started,minutes_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,attempted_three_point_field_goals,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points,player_efficiency_rating,true_shooting_percentage,three_point_attempt_rate,free_throw_attempt_rate,offensive_rebound_percentage,defensive_rebound_percentage,total_rebound_percentage,assist_percentage,steal_percentage,block_percentage,turnover_percentage,usage_percentage,offensive_win_shares,defensive_win_shares,win_shares,win_shares_per_48_minutes,offensive_box_plus_minus,defensive_box_plus_minus,box_plus_minus,value_over_replacement_player,fg_percentage,three_point_percentage,ft_percentage,effective_fg_percentage,points_per_36,assists_per_36,offensive_rebounds_per_36,defensive_rebounds_per_36,steals_per_36,blocks_per_36,turnovers_per_36,personal_fouls_per_36,total_rebounds_per_36,points_per_game,assists_per_game,total_rebounds_per_game,steals_per_game,blocks_per_game,turnovers_per_game,minutes_per_game,assist_to_turnover_ratio,stocks_per_game,win_shares_per_game
2,abdursh01,2001,Shareef Abdur-Rahim,SMALL FORWARD,24,VANCOUVER GRIZZLIES,81,81,3241,604,1280,12,64,443,531,175,560,250,90,77,231,238,1663,19.1,0.549,0.050,0.415,6.2,19.6,13.0,14.3,1.5,1.6,13.2,24.6,5.6,2.9,8.5,0.126,1.7,0.1,1.8,3.1,0.471875,0.187500,0.834275,0.476562,18.472077,2.776921,1.943844,6.220302,0.999691,0.855292,2.565875,2.643629,8.164147,20.530864,3.086420,9.074074,1.111111,0.950617,2.851852,40.012346,1.082251,2.061728,0.104938
442,abdursh01,2002,Shareef Abdur-Rahim,POWER FORWARD,25,ATLANTA HAWKS,77,77,2980,598,1297,21,70,419,523,198,498,239,98,81,250,214,1636,19.8,0.536,0.054,0.403,7.6,19.2,13.3,15.1,1.7,2.0,14.1,27.0,4.1,3.1,7.2,0.116,1.9,-0.2,1.7,2.8,0.461064,0.300000,0.801147,0.469160,19.763758,2.887248,2.391946,6.016107,1.183893,0.978523,3.020134,2.585235,8.408054,21.246753,3.103896,9.038961,1.272727,1.051948,3.246753,38.701299,0.956000,2.324675,0.093506
882,abdursh01,2003,Shareef Abdur-Rahim,POWER FORWARD,26,ATLANTA HAWKS,81,81,3087,566,1183,21,60,455,541,175,502,242,87,38,212,240,1608,19.9,0.566,0.051,0.457,6.7,17.8,12.5,14.7,1.5,0.9,13.0,24.2,7.4,2.3,9.7,0.151,2.3,-0.7,1.6,2.8,0.478445,0.350000,0.841035,0.487320,18.752187,2.822157,2.040816,5.854227,1.014577,0.443149,2.472303,2.798834,7.895044,19.851852,2.987654,8.358025,1.074074,0.469136,2.617284,38.111111,1.141509,1.543210,0.119753
1309,abdursh01,2004,Shareef Abdur-Rahim,POWER FORWARD,27,ATLANTA HAWKS/PORTLAND TRAIL BLAZERS,85,56,2684,501,1054,9,34,373,429,189,450,174,68,37,184,222,1384,19.9,0.557,0.032,0.407,8.2,19.0,13.6,12.3,1.4,1.0,12.9,24.4,6.1,2.0,8.1,0.145,2.3,-0.7,1.6,2.4,0.475332,0.264706,0.869464,0.479602,18.563338,2.333830,2.535022,6.035768,0.912072,0.496274,2.467958,2.977645,8.570790,16.282353,2.047059,7.517647,0.800000,0.435294,2.164706,31.576471,0.945652,1.235294,0.095294
1751,abdursh01,2005,Shareef Abdur-Rahim,POWER FORWARD,28,PORTLAND TRAIL BLAZERS,54,49,1867,337,670,15,39,220,254,123,269,111,49,26,117,150,909,18.7,0.581,0.058,0.379,7.9,16.0,12.1,10.7,1.4,1.0,13.0,22.1,3.9,1.5,5.4,0.139,1.6,-0.6,0.9,1.4,0.502985,0.384615,0.866142,0.514179,17.527584,2.140332,2.371719,5.186931,0.944831,0.501339,2.256026,2.892341,7.558650,16.833333,2.055556,7.259259,0.907407,0.481481,2.166667,34.574074,0.948718,1.388889,0.100000
2215,abdursh01,2006,Shareef Abdur-Rahim,POWER FORWARD,29,SACRAMENTO KINGS,72,30,1961,332,632,5,22,218,278,106,251,149,48,42,108,227,887,17.2,0.588,0.035,0.440,6.4,14.8,10.6,13.2,1.3,1.6,12.5,20.1,4.0,2.2,6.2,0.152,0.5,0.4,0.9,1.4,0.525316,0.227273,0.784173,0.529272,16.283529,2.735339,1.945946,4.607853,0.881183,0.771035,1.982662,4.167262,6.553799,12.319444,2.069444,4.958333,0.666667,0.583333,1.500000,27.236111,1.379630,1.250000,0.086111
2673,abdursh01,2007,Shareef Abdur-Rahim,CENTER,30,SACRAMENTO KINGS,80,45,2015,310,654,3,20,170,234,122,276,109,53,40,116,243,793,13.1,0.524,0.031,0.358,7.0,16.4,11.6,9.2,1.3,1.5,13.3,19.5,1.1,1.7,2.8,0.067,-2.0,-0.5,-2.5,-0.2,0.474006,0.150000,0.726496,0.476300,14.167742,1.947395,2.179653,4.931017,0.946898,0.714640,2.072457,4.341439,7.110670,9.912500,1.362500,4.975000,0.662500,0.500000,1.450000,25.187500,0.939655,1.162500,0.035000
3131,abdursh01,2008,Shareef Abdur-Rahim,POWER FORWARD,31,SACRAMENTO KINGS,6,0,51,3,14,0,0,4,4,6,4,4,1,0,1,9,10,5.5,0.317,0.000,0.286,14.2,9.1,11.6,11.1,1.0,0.0,6.0,14.7,0.0,0.0,0.0,-0.005,-4.4,-2.5,-6.9,-0.1,0.214286,NaN,1.000000,0.214286,7.058824,2.823529,4.235294,2.823529,0.705882,0.000000,0.705882,6.352941,7.058824,1.666667,0.666667,1.666667,0.166667,0.000000,0.166667,8.500000,4.000000,0.166667,0.000000

In [8]:
sar_advanced_stats_df = advanced_stats_df[advanced_stats_df['slug'] == 'abdursh01']
sar_advanced_stats_df

,slug,season_end_year,name,positions,age,team,games_played,minutes_played,player_efficiency_rating,true_shooting_percentage,three_point_attempt_rate,free_throw_attempt_rate,offensive_rebound_percentage,defensive_rebound_percentage,total_rebound_percentage,assist_percentage,steal_percentage,block_percentage,turnover_percentage,usage_percentage,offensive_win_shares,defensive_win_shares,win_shares,win_shares_per_48_minutes,offensive_box_plus_minus,defensive_box_plus_minus,box_plus_minus,value_over_replacement_player
5,abdursh01,2001,Shareef Abdur-Rahim,SMALL FORWARD,24,VANCOUVER GRIZZLIES,81,3241,19.1,0.549,0.050,0.415,6.2,19.6,13.0,14.3,1.5,1.6,13.2,24.6,5.6,2.9,8.5,0.126,1.7,0.1,1.8,3.1
465,abdursh01,2002,Shareef Abdur-Rahim,POWER FORWARD,25,ATLANTA HAWKS,77,2980,19.8,0.536,0.054,0.403,7.6,19.2,13.3,15.1,1.7,2.0,14.1,27.0,4.1,3.1,7.2,0.116,1.9,-0.2,1.7,2.8
898,abdursh01,2003,Shareef Abdur-Rahim,POWER FORWARD,26,ATLANTA HAWKS,81,3087,19.9,0.566,0.051,0.457,6.7,17.8,12.5,14.7,1.5,0.9,13.0,24.2,7.4,2.3,9.7,0.151,2.3,-0.7,1.6,2.8
1359,abdursh01,2004,Shareef Abdur-Rahim,POWER FORWARD,27,None,85,2684,19.9,0.557,0.032,0.407,8.2,19.0,13.6,12.3,1.4,1.0,12.9,24.4,6.1,2.0,8.1,0.145,2.3,-0.7,1.6,2.4
1878,abdursh01,2005,Shareef Abdur-Rahim,POWER FORWARD,28,PORTLAND TRAIL BLAZERS,54,1867,18.7,0.581,0.058,0.379,7.9,16.0,12.1,10.7,1.4,1.0,13.0,22.1,3.9,1.5,5.4,0.139,1.6,-0.6,0.9,1.4
2338,abdursh01,2006,Shareef Abdur-Rahim,POWER FORWARD,29,SACRAMENTO KINGS,72,1961,17.2,0.588,0.035,0.440,6.4,14.8,10.6,13.2,1.3,1.6,12.5,20.1,4.0,2.2,6.2,0.152,0.5,0.4,0.9,1.4
2797,abdursh01,2007,Shareef Abdur-Rahim,CENTER,30,SACRAMENTO KINGS,80,2015,13.1,0.524,0.031,0.358,7.0,16.4,11.6,9.2,1.3,1.5,13.3,19.5,1.1,1.7,2.8,0.067,-2.0,-0.5,-2.5,-0.2
3556,abdursh01,2008,Shareef Abdur-Rahim,POWER FORWARD,31,SACRAMENTO KINGS,6,51,5.5,0.317,0.000,0.286,14.2,9.1,11.6,11.1,1.0,0.0,6.0,14.7,0.0,0.0,0.0,-0.005,-4.4,-2.5,-6.9,-0.1

In [9]:
conn = sqlite3.connect('nba_stats.db')

query = 'SELECT * FROM per_100_stats'
per_100_stats_df = pd.read_sql_query(query, conn)

conn.close()

per_100_stats_df.head()

,season_end_year,player_id,player_name,nickname,team_id,team_abbreviation,age,gp,w,l,w_pct,per_100_min,per_100_fgm,per_100_fga,per_100_fg_pct,per_100_fg3m,per_100_fg3a,per_100_fg3_pct,per_100_ftm,per_100_fta,per_100_ft_pct,per_100_oreb,per_100_dreb,per_100_reb,per_100_ast,per_100_tov,per_100_stl,per_100_blk,per_100_blka,per_100_pf,per_100_pfd,per_100_pts,per_100_plus_minus,per_100_nba_fantasy_pts,dd2,td3,per_100_wnba_fantasy_pts,gp_rank,w_rank,l_rank,w_pct_rank,min_rank,fgm_rank,fga_rank,fg_pct_rank,fg3m_rank,fg3a_rank,fg3_pct_rank,ftm_rank,fta_rank,ft_pct_rank,oreb_rank,dreb_rank,reb_rank,ast_rank,tov_rank,stl_rank,blk_rank,blka_rank,pf_rank,pfd_rank,pts_rank,plus_minus_rank,nba_fantasy_pts_rank,dd2_rank,td3_rank,wnba_fantasy_pts_rank,team_count,slug
0,2001,920,A.C. Green,A.C.,1610612748,MIA,37.0,82,50,32,0.610,53.1,5.4,12.2,0.444,0.0,0.2,0.000,3.0,4.2,0.712,4.0,7.7,11.8,1.5,1.7,1.1,0.3,1.1,4.5,0.0,13.8,3.9,32.7,3,0,29.9,2,38,163,130,33,310,345,171,295,295,295,248,242,259,115,128,123,376,401,326,328,204,273,58,328,90,356,126,26,367,1,greenac01
1,2001,2062,A.J. Guyton,A.J.,1610612741,CHI,23.0,33,6,27,0.182,53.6,6.6,16.4,0.406,2.3,5.9,0.391,1.3,1.5,0.833,0.9,2.2,3.1,5.5,2.0,0.8,0.4,0.3,3.0,0.0,16.9,-12.4,30.3,0,0,30.1,334,381,231,419,21,202,186,293,51,59,62,390,409,71,367,429,427,117,368,392,286,417,403,112,227,408,388,224,26,365,1,guytoaj01
2,2001,243,Aaron McKie,Aaron,1610612755,PHI,28.0,76,51,25,0.671,51.5,7.3,15.4,0.473,1.1,3.7,0.312,3.2,4.2,0.768,0.7,6.0,6.7,8.1,4.4,2.3,0.2,1.2,3.8,0.0,18.9,7.2,42.2,8,2,39.8,120,31,251,57,162,157,216,106,149,143,181,213,239,176,386,214,277,45,39,75,363,168,331,112,168,32,148,77,4,144,1,mckieaa01
3,2001,1425,Aaron Williams,Aaron,1610612751,NJN,29.0,82,26,56,0.317,51.6,6.6,14.4,0.457,0.0,0.0,0.000,5.4,6.8,0.787,4.7,8.4,13.0,1.9,2.9,1.3,2.5,1.5,7.0,0.0,18.5,-8.4,45.6,12,0,41.1,2,223,12,358,157,210,263,141,295,353,295,61,70,146,76,99,89,329,220,287,51,97,89,112,185,364,94,53,26,118,1,williaa01
4,2001,228,Adam Keefe,Adam,1610612744,GSW,31.0,67,14,53,0.209,50.5,3.8,9.5,0.403,0.1,0.2,0.333,2.3,3.8,0.619,5.4,7.1,12.5,2.2,2.4,1.7,1.2,1.2,6.1,0.0,10.1,-10.3,34.6,0,0,30.6,192,318,18,407,283,400,402,300,268,306,145,303,274,345,36,157,101,311,307,184,141,171,140,112,399,383,323,224,26,352,1,keefead01

In [10]:
conn = sqlite3.connect('nba_stats.db')

query = 'SELECT * FROM league_averages'
league_averages_df = pd.read_sql_query(query, conn)

conn.close()

league_averages_df

,season_label,average_age,average_height,average_weight,league_avg_games_played,league_avg_per_100_fgm,league_avg_per_100_fga,league_avg_per_100_fg3m,league_avg_per_100_fg3a,league_avg_per_100_ftm,league_avg_per_100_fta,league_avg_per_100_oreb,league_avg_per_100_dreb,league_avg_per_100_reb,league_avg_per_100_ast,league_avg_per_100_stl,league_avg_per_100_blk,league_avg_per_100_tov,league_avg_per_100_pf,league_avg_per_100_pts,league_avg_fg_percentage,league_avg_three_point_percentage,league_avg_ft_percentage,league_avg_pace,league_avg_effective_fg_percentage,league_avg_turnover_percentage,league_avg_offensive_rebound_percentage,league_avg_ft_per_fga,league_avg_offensive_rating,league_avg_true_shooting_percentage,season_end_year
0,2000-01,27.7,6-7,217,1189,38.8,87.6,5.3,14.9,20.2,27.0,13.0,33.1,46.1,23.7,8.5,5.7,16.4,24.3,103.0,0.443,0.354,0.748,91.3,0.473,14.1,28.2,0.231,103.0,0.518,2001
1,2001-02,27.4,6-7,218,1189,39.6,89.0,5.7,16.1,19.6,26.1,13.4,33.0,46.4,24.0,8.5,5.7,15.8,23.2,104.5,0.445,0.354,0.752,90.7,0.477,13.6,28.9,0.221,104.5,0.520,2002
2,2002-03,27.2,6-7,219,1189,38.9,88.1,5.6,16.0,20.2,26.6,13.1,33.0,46.1,23.4,8.7,5.5,16.3,23.7,103.6,0.442,0.349,0.758,91.0,0.474,14.0,28.5,0.229,103.6,0.519,2003
3,2003-04,27.0,6-7,220,1189,38.6,88.0,5.7,16.4,20.1,26.7,13.3,33.2,46.5,23.5,8.7,5.6,16.5,23.6,102.9,0.439,0.347,0.752,90.1,0.471,14.2,28.6,0.228,102.9,0.516,2004
4,2004-05,26.9,6-7,220,1230,39.2,87.7,6.1,17.2,21.5,28.4,13.1,32.6,45.7,23.2,8.2,5.3,15.8,24.7,106.1,0.447,0.356,0.756,90.9,0.482,13.6,28.7,0.245,106.1,0.529,2005
5,2005-06,26.5,6-7,220,1230,39.2,86.5,6.3,17.5,21.5,28.8,12.2,32.6,44.8,22.6,7.8,5.1,15.8,24.9,106.2,0.454,0.358,0.745,90.5,0.490,13.7,27.3,0.248,106.2,0.536,2006
6,2006-07,26.6,6-7,219,1230,39.4,85.9,6.5,18.3,21.1,28.1,12.0,32.3,44.3,22.9,7.8,5.0,16.3,24.0,106.5,0.458,0.358,0.752,91.9,0.496,14.2,27.1,0.246,106.5,0.541,2007
7,2007-08,26.8,6-7,220,1230,40.1,87.7,7.1,19.5,20.3,26.8,12.0,33.1,45.2,23.4,7.8,5.1,15.2,22.6,107.5,0.457,0.362,0.755,92.4,0.497,13.2,26.7,0.231,107.5,0.540,2008
8,2008-09,26.6,6-7,221,1230,40.2,87.7,7.2,19.6,20.7,26.8,12.0,32.8,44.7,22.7,7.9,5.2,15.2,22.8,108.3,0.459,0.367,0.771,91.7,0.500,13.3,26.7,0.236,108.3,0.544,2009
9,2009-10,26.6,6-7,222,1230,40.4,87.5,6.9,19.4,19.9,26.3,11.7,32.9,44.7,22.8,7.7,5.2,15.2,22.3,107.6,0.461,0.355,0.759,92.7,0.501,13.3,26.3,0.228,107.6,0.543,2010
10,2010-11,26.6,6-7,223,1230,40.1,87.5,7.0,19.4,20.0,26.3,11.8,32.8,44.6,23.2,7.9,5.2,15.4,22.3,107.3,0.459,0.358,0.763,92.1,0.498,13.4,26.4,0.229,107.3,0.541,2011
11,2011-12,26.6,6-7,223,990,39.6,88.5,7.0,20.0,18.4,24.4,12.4,33.5,45.8,22.8,8.3,5.5,15.8,21.3,104.6,0.448,0.349,0.752,91.3,0.487,13.8,27.0,0.208,104.6,0.527,2012
12,2012-13,26.7,6-7,223,1229,40.1,88.5,7.7,21.5,18.0,23.9,12.0,33.4,45.4,23.9,8.4,5.5,15.7,21.4,105.8,0.453,0.359,0.753,92.0,0.496,13.7,26.5,0.204,105.8,0.535,2013
13,2013-14,26.5,6-7,223,1230,39.8,87.6,8.2,22.7,18.8,24.9,11.5,33.6,45.1,23.2,8.1,5.0,15.5,21.9,106.6,0.454,0.360,0.756,93.9,0.501,13.6,25.5,0.215,106.6,0.541,2014
14,2014-15,26.7,6-7,223,1230,39.6,88.3,8.3,23.7,18.1,24.1,11.5,34.2,45.7,23.3,8.2,5.1,15.2,21.4,105.6,0.449,0.350,0.750,93.9,0.496,13.3,25.1,0.205,105.6,0.534,2015
15,2015-16,26.7,6-7,222,1230,39.6,87.6,8.8,25.0,18.3,24.2,10.8,34.6,45.3,23.1,8.1,5.1,14.9,21.0,106.4,0.452,0.354,0.757,95.8,0.502,13.2,23.8,0.209,106.4,0.541,2016
16,2016-17,26.6,6-7,222,1230,40.2,88.0,9.9,27.8,18.4,23.8,10.4,34.4,44.8,23.3,7.9,4.9,14.4,20.5,108.8,0.457,0.358,0.772,96.4,0.514,12.7,23.3,0.209,108.8,0.552,2017
17,2017-18,26.4,6-7,221,1230,40.5,87.9,10.7,29.6,17.0,22.1,9.9,34.5,44.4,23.7,7.9,4.9,14.6,20.3,108.6,0.460,0.362,0.767,97.3,0.521,13.0,22.3,0.193,108.6,0.556,2018
18,2018-19,26.3,6-6,220,1230,40.8,88.6,11.3,31.8,17.6,22.9,10.3,34.6,44.8,24.4,7.6,4.9,14.0,20.8,110.4,0.461,0.355,0.766,100.0,0.524,12.4,22.9,0.198,110.4,0.560,2019
19,2019-20,26.1,6-6,218,1059,40.4,87.9,12.1,33.8,17.7,22.9,10.0,34.4,44.4,24.1,7.6,4.8,14.4,20.6,110.6,0.460,0.358,0.773,100.3,0.529,12.8,22.5,0.201,110.6,0.565,2020
20,2020-21,26.1,6-6,218,1080,41.3,88.6,12.7,34.7,17.0,21.9,9.9,34.5,44.4,24.9,7.6,4.9,13.9,19.3,112.3,0.466,0.367,0.778,99.2,0.538,12.4,22.2,0.192,112.3,0.572,2021
21,2021-22,26.1,6-6,216,1230,41.1,89.2,12.6,35.6,17.1,22.1,10.5,34.5,45.0,24.9,7.7,4.8,13.9,19.9,112.0,0.461,0.354,0.775,98.2,0.532,12.3,23.2,0.192,112.0,0.566,2022
22,2022-23,26.1,6-6,217,1230,42.0,88.4,12.4,34.2,18.4,23.6,10.4,33.0,43.5,25.3,7.3,4.7,14.1,20.0,114.8,0.475,0.361,0.782,99.2,0.545,12.5,24.0,0.208,114.8,0.581,2023
23,2023-24,26.4,6-6,217,1230,42.6,89.7,13.0,35.4,17.2,21.9,10.7,33.3,43.9,26.9,7.5,5.2,13.7,18.9,115.3,0.474,0.366,0.784,98.5,0.547,12.1,24.2,0.192,115.3,0.580,2024
24,2024-25,26.3,6-7,216,1230,42.0,89.8,13.6,37.8,17.0,21.8,11.2,33.2,44.4,26.7,8.3,4.9,14.4,18.7,114.5,0.467,0.360,0.780,98.8,0.543,12.6,25.2,0.189,114.5,0.576,2025
25,2025-26,26.1,6-7,216,1230,42.0,89.2,13.3,37.0,18.4,23.5,11.4,32.4,43.8,26.8,8.4,4.8,14.5,19.9,115.7,0.471,0.360,0.783,99.4,0.546,12.7,26.0,0.206,115.7,0.581,2026

In [11]:
conn = sqlite3.connect('nba_stats.db')

query = 'SELECT * FROM team_per_100_stats'

team_per_100_stats_df = pd.read_sql_query(query, conn)
conn.close()
team_per_100_stats_df

,season_end_year,team_id,team_name,gp,w,l,w_pct,per_100_min,per_100_fgm,per_100_fga,per_100_fg_pct,per_100_fg3m,per_100_fg3a,per_100_fg3_pct,per_100_ftm,per_100_fta,per_100_ft_pct,per_100_oreb,per_100_dreb,per_100_reb,per_100_ast,per_100_tov,per_100_stl,per_100_blk,per_100_blka,per_100_pf,per_100_pfd,per_100_pts,per_100_plus_minus,gp_rank,w_rank,l_rank,w_pct_rank,min_rank,fgm_rank,fga_rank,fg_pct_rank,fg3m_rank,fg3a_rank,fg3_pct_rank,ftm_rank,fta_rank,ft_pct_rank,oreb_rank,dreb_rank,reb_rank,ast_rank,tov_rank,stl_rank,blk_rank,blka_rank,pf_rank,pfd_rank,pts_rank,plus_minus_rank
0,2001,1610612737,Atlanta Hawks,82,25,57,0.305,51.3,37.4,86.7,0.431,4.3,12.1,0.357,17.9,23.5,0.759,13.4,32.4,45.7,20.3,17.8,8.2,5.0,6.7,24.2,0.1,96.9,-5.5,1,25,25,25,19,21,11,22,22,24,11,28,28,13,9,17,13,29,28,17,22,26,15,9,27,25
1,2001,1610612738,Boston Celtics,82,36,46,0.439,51.2,35.8,83.7,0.428,7.6,21.1,0.363,20.9,28.3,0.740,11.6,30.5,42.1,22.0,16.6,9.9,4.3,5.7,25.2,0.0,100.1,-2.3,1,20,20,20,20,29,28,25,1,1,8,7,7,20,26,26,29,22,20,2,28,15,23,25,17,20
2,2001,1610612766,Charlotte Hornets,82,46,36,0.561,52.6,37.0,85.9,0.431,4.5,13.0,0.346,21.1,28.4,0.745,13.7,34.5,48.1,25.1,15.6,8.8,6.0,5.0,23.2,0.1,99.7,2.3,1,14,14,14,9,23,14,23,19,20,18,6,6,19,7,3,2,6,10,10,10,7,9,19,19,14
3,2001,1610612741,Chicago Bulls,82,15,67,0.183,53.0,36.3,85.6,0.424,4.4,12.7,0.346,18.8,25.5,0.739,12.4,30.2,42.6,24.2,17.3,9.0,5.1,5.7,25.4,0.0,95.9,-10.0,1,29,29,29,3,27,18,27,20,21,17,25,20,21,19,29,27,10,25,6,21,16,24,22,29,29
4,2001,1610612739,Cleveland Cavaliers,82,30,52,0.366,52.1,38.0,85.8,0.442,2.9,8.7,0.334,20.5,26.8,0.765,13.3,32.1,45.4,22.4,17.7,8.4,5.7,7.1,25.0,0.1,99.3,-4.6,1,23,23,23,12,16,16,14,29,29,24,10,12,8,10,20,15,18,27,16,12,29,22,7,22,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,2026,1610612758,Sacramento Kings,82,22,60,0.268,48.0,41.4,88.7,0.467,10.2,30.1,0.340,17.5,22.7,0.772,11.5,30.6,42.1,25.4,14.3,8.0,4.5,4.7,19.6,18.2,110.6,-10.0,1,26,26,26,13,17,15,18,30,30,29,21,19,21,12,25,21,23,15,21,20,14,16,26,26,28
772,2026,1610612759,San Antonio Spurs,82,62,20,0.756,47.7,43.0,89.1,0.483,13.5,37.6,0.359,19.2,24.4,0.787,11.3,35.3,46.6,27.8,13.3,7.5,5.4,4.5,18.7,20.0,118.7,8.2,1,2,2,2,18,6,10,6,14,13,15,8,11,12,14,2,4,8,5,24,6,9,6,12,3,2
773,2026,1610612761,Toronto Raptors,82,46,36,0.561,48.4,42.7,88.7,0.482,11.4,32.2,0.354,18.1,23.5,0.769,10.9,31.3,42.2,29.6,13.7,8.8,4.8,5.0,20.9,19.8,115.0,2.8,1,11,11,11,9,8,14,7,26,25,21,19,16,22,17,21,20,1,7,8,14,19,27,16,15,11
774,2026,1610612762,Utah Jazz,82,22,60,0.268,46.3,40.8,87.3,0.467,12.1,35.1,0.345,19.0,24.2,0.786,11.5,30.5,42.0,28.4,14.9,8.5,3.6,5.6,20.3,19.5,112.7,-8.1,1,26,26,26,29,22,20,17,22,20,25,9,12,13,11,27,23,5,22,14,30,27,21,20,22,27
775,2026,1610612764,Washington Wizards,82,17,65,0.207,46.8,40.6,87.8,0.463,12.7,35.3,0.359,15.8,20.6,0.766,10.7,30.0,40.7,24.3,15.2,7.8,5.4,5.3,20.7,17.4,109.7,-11.6,1,30,30,30,26,24,19,22,20,19,16,28,27,23,20,29,29,28,24,22,7,23,25,30,29,30

In [12]:
conn = sqlite3.connect('nba_stats.db')

query = 'SELECT * FROM nba_per_100_averages'

league_per_100_stats_df = pd.read_sql_query(query, conn)
conn.close()
league_per_100_stats_df

,season_end_year,per_100_fgm,per_100_fga,per_100_fg_pct,per_100_fg3m,per_100_fg3a,per_100_fg3_pct,per_100_ftm,per_100_fta,per_100_ft_pct,per_100_oreb,per_100_dreb,per_100_reb,per_100_ast,per_100_tov,per_100_stl,per_100_blk,per_100_blka,per_100_pf,per_100_pfd,per_100_pts,per_100_plus_minus
0,2001,38.224138,86.313793,0.442862,5.189655,14.675862,0.351828,19.913793,26.641379,0.748759,12.834483,32.658621,45.482759,23.324138,16.120690,8.365517,5.631034,5.627586,23.941379,0.072414,101.555172,1.724138e-02
1,2002,39.062069,87.779310,0.445069,5.613793,15.906897,0.351759,19.348276,25.717241,0.752586,13.210345,32.572414,45.793103,23.675862,15.620690,8.410345,5.637931,5.644828,22.944828,0.120690,103.093103,-1.379310e-02
2,2003,38.365517,86.810345,0.442034,5.506897,15.782759,0.346621,19.900000,26.255172,0.758103,12.944828,32.506897,45.458621,23.100000,16.031034,8.531034,5.389655,5.393103,23.368966,0.086207,102.162069,0.000000e+00
3,2004,38.017241,86.658621,0.438483,5.624138,16.186207,0.345552,19.755172,26.265517,0.752414,13.144828,32.703448,45.841379,23.134483,16.265517,8.606897,5.496552,5.496552,23.300000,0.048276,101.393103,1.379310e-02
4,2005,38.650000,86.400000,0.447433,6.023333,16.933333,0.353167,21.190000,28.030000,0.756500,12.930000,32.100000,45.023333,22.886667,15.603333,8.076667,5.233333,5.240000,24.353333,0.043333,104.506667,6.666667e-03
5,2006,38.736667,85.393333,0.453733,6.176667,17.263333,0.356867,21.200000,28.446667,0.745900,12.090000,32.206667,44.290000,22.276667,15.590000,7.743333,5.096667,5.073333,24.613333,24.556667,104.856667,6.666667e-03
6,2007,38.946667,85.006667,0.458333,6.450000,18.036667,0.356800,20.916667,27.810000,0.752967,11.876667,31.933333,43.813333,22.683333,16.133333,7.720000,4.916667,4.896667,23.713333,23.700000,105.276667,6.666667e-03
7,2008,39.613333,86.673333,0.457167,6.953333,19.223333,0.360233,20.020000,26.503333,0.755600,11.926667,32.736667,44.656667,23.130000,14.990000,7.730000,5.040000,5.026667,22.350000,22.340000,106.196667,1.666667e-02
8,2009,39.740000,86.633333,0.458867,7.113333,19.400000,0.365433,20.406667,26.476667,0.771300,11.823333,32.403333,44.233333,22.453333,15.010000,7.783333,5.140000,5.140000,22.536667,22.530000,106.983333,4.333333e-02
9,2010,39.993333,86.703333,0.461467,6.813333,19.240000,0.352767,19.770000,26.056667,0.759133,11.636667,32.653333,44.303333,22.546667,15.090000,7.653333,5.163333,5.150000,22.126667,22.146667,106.583333,3.666667e-02
10,2011,39.783333,86.743333,0.458733,6.883333,19.223333,0.356267,19.876667,26.026667,0.763300,11.650000,32.550000,44.206667,22.970000,15.216667,7.830000,5.196667,5.196667,22.126667,22.130000,106.313333,3.333333e-02
11,2012,39.213333,87.566667,0.447933,6.893333,19.750000,0.347233,18.163333,24.140000,0.752667,12.223333,33.133333,45.363333,22.570000,15.676667,8.250000,5.473333,5.480000,21.040000,21.036667,103.496667,-6.666667e-03
12,2013,39.636667,87.590000,0.453067,7.636667,21.303333,0.357567,17.833333,23.686667,0.753467,11.933333,33.070000,45.006667,23.640000,15.530000,8.330000,5.496667,5.480000,21.193333,21.196667,104.760000,2.960595e-17
13,2014,39.476667,86.866667,0.454600,8.090000,22.496667,0.358767,18.656667,24.666667,0.757067,11.416667,33.316667,44.743333,23.030000,15.333333,8.030000,4.933333,4.936667,21.680000,21.660000,105.683333,-2.220446e-17
14,2015,39.290000,87.516667,0.449000,8.206667,23.450000,0.349100,17.960000,23.930000,0.750667,11.410000,33.943333,45.346667,23.070000,15.040000,8.090000,5.020000,5.026667,21.166667,21.170000,104.740000,-1.000000e-02
15,2016,39.303333,86.956667,0.452200,8.743333,24.740000,0.352767,18.190000,24.036667,0.757967,10.703333,34.290000,45.006667,22.906667,14.783333,8.066667,5.090000,5.093333,20.833333,20.846667,105.560000,1.480297e-17
16,2017,40.003333,87.513333,0.457200,9.890000,27.650000,0.357167,18.260000,23.670000,0.771800,10.390000,34.193333,44.576667,23.173333,14.280000,7.900000,4.856667,4.856667,20.380000,20.400000,108.156667,1.333333e-02
17,2018,40.163333,87.306667,0.460267,10.633333,29.406667,0.361733,16.850000,21.973333,0.767500,9.860000,34.270000,44.130000,23.550000,14.463333,7.840000,4.880000,4.883333,20.146667,20.150000,107.840000,-3.333333e-03
18,2019,40.536667,88.026667,0.460467,11.213333,31.593333,0.355500,17.443333,22.753333,0.766967,10.210000,34.356667,44.560000,24.253333,13.893333,7.526667,4.886667,4.890000,20.630000,20.616667,109.720000,-1.000000e-02
19,2020,40.216667,87.476667,0.459900,12.006667,33.563333,0.357767,17.560000,22.743333,0.772233,9.943333,34.176667,44.120000,24.003333,14.333333,7.540000,4.810000,4.843333,20.460000,20.446667,109.983333,-1.633333e-01
20,2021,41.073333,88.113333,0.466067,12.673333,34.530000,0.366033,16.903333,21.733333,0.778667,9.790000,34.363333,44.143333,24.713333,13.783333,7.546667,4.853333,4.856667,19.236667,19.236667,111.713333,2.000000e-02
21,2022,40.900000,88.703333,0.461233,12.516667,35.423333,0.353567,17.050000,22.013333,0.775000,10.410000,34.360000,44.760000,24.813333,13.856667,7.673333,4.743333,4.746667,19.773333,19.783333,111.383333,2.000000e-02
22,2023,41.743333,87.813333,0.475467,12.266667,34.033333,0.360133,18.300000,23.416667,0.782000,10.373333,32.823333,43.206667,25.183333,14.013333,7.256667,4.630000,4.626667,19.886667,19.886667,114.076667,3.333333e-02
23,2024,42.296667,89.163333,0.474300,12.876667,35.203333,0.365667,17.083333,21.790000,0.783967,10.590000,33.083333,43.683333,26.743333,13.650000,7.493333,5.160000,5.156667,18.780000,18.786667,114.546667,3.666667e-02
24,2025,41.630000,89.136667,0.467233,13.526667,37.556667,0.359967,16.880000,21.653333,0.780400,11.110000,32.950000,44.053333,26.516667,14.276667,8.193333,4.863333,4.860000,18.576667,18.576667,113.680000,1.333333e-02
25,2026,41.663333,88.450000,0.471067,13.223333,36.726667,0.359333,18.243333,23.300000,0.782833,11.303333,32.153333,43.466667,26.540000,14.410000,8.363333,4.810000,4.803333,19.733333,19.716667,114.786667,4.000000e-02

In [13]:
conn = sqlite3.connect('nba_stats.db')

query = 'SELECT * FROM nba_advanced_averages'

team_advanced_averages_df = pd.read_sql_query(query, conn)
conn.close()
team_advanced_averages_df

,season_end_year,min,e_off_rating,off_rating,e_def_rating,def_rating,e_net_rating,net_rating,ast_pct,ast_to,ast_ratio,oreb_pct,dreb_pct,reb_pct,tm_tov_pct,efg_pct,ts_pct,e_pace,pace,pace_per40,poss,pie
0,2001,3969.103448,100.234483,101.555172,100.220690,101.544828,1.379310e-02,1.034483e-02,0.610069,1.455517,16.813793,0.311621,0.688034,0.500034,0.161207,0.473069,0.518034,93.800000,92.584138,77.153448,7655.517241,0.500069
1,2002,3963.241379,101.575862,103.093103,101.603448,103.110345,-1.379310e-02,-1.379310e-02,0.606069,1.525517,16.982759,0.317069,0.682690,0.500034,0.156207,0.477034,0.520276,93.344828,91.957241,76.630345,7592.586207,0.499931
2,2003,3968.344828,100.706897,102.162069,100.703448,102.158621,1.724138e-02,-6.896552e-03,0.601690,1.456552,16.658621,0.314207,0.686034,0.500034,0.160310,0.473759,0.519172,93.637931,92.300345,76.915862,7630.758621,0.499448
3,2004,3963.931034,100.031034,101.393103,100.017241,101.372414,2.068966e-02,2.413793e-02,0.608172,1.436897,16.665517,0.316655,0.683103,0.500069,0.162655,0.471034,0.516103,92.700000,91.450000,76.208621,7551.862069,0.500172
4,2005,3966.666667,103.063333,104.506667,103.073333,104.510000,-6.666667e-03,-6.666667e-03,0.592233,1.475000,16.543333,0.318300,0.681933,0.500200,0.156033,0.482233,0.529400,93.560000,92.274333,76.895333,7625.166667,0.499900
5,2006,3970.333333,103.410000,104.856667,103.406667,104.846667,3.700743e-17,6.666667e-03,0.575067,1.441667,16.270000,0.306067,0.693733,0.500100,0.155900,0.489800,0.535533,92.993333,91.704667,76.419667,7585.533333,0.499933
6,2007,3971.666667,103.720000,105.276667,103.706667,105.263333,3.333333e-03,1.333333e-02,0.582200,1.415333,16.566667,0.304267,0.695800,0.500100,0.161333,0.496167,0.541433,94.330000,92.931000,77.443333,7689.300000,0.500067
7,2008,3960.666667,104.730000,106.196667,104.720000,106.190000,1.000000e-02,2.000000e-02,0.583500,1.552667,16.820000,0.301367,0.698367,0.500100,0.149900,0.497400,0.540233,94.790000,93.485000,77.904000,7713.800000,0.499867
8,2009,3964.333333,105.446667,106.983333,105.396667,106.940000,4.333333e-02,4.333333e-02,0.565133,1.504000,16.416667,0.302567,0.697600,0.500000,0.150100,0.499833,0.544400,94.116667,92.757333,77.298333,7660.800000,0.500533
9,2010,3963.333333,104.900000,106.583333,104.863333,106.553333,2.000000e-02,2.333333e-02,0.563433,1.502000,16.480000,0.301267,0.698667,0.500133,0.150900,0.500933,0.542967,95.093333,93.599000,78.000000,7728.233333,0.500400
10,2011,3967.000000,104.486667,106.313333,104.440000,106.276667,3.666667e-02,4.000000e-02,0.577200,1.517333,16.746667,0.301567,0.697767,0.499900,0.152167,0.498533,0.541533,94.536667,92.898000,77.415667,7677.666667,0.500367
11,2012,3193.666667,101.830000,103.496667,101.836667,103.493333,2.960595e-17,-1.000000e-02,0.575267,1.449667,16.410000,0.305867,0.693700,0.500033,0.156767,0.487300,0.527033,93.756667,92.249333,76.873667,6137.733333,0.499933
12,2013,3963.133333,103.106667,104.760000,103.130000,104.766667,-1.000000e-02,-3.333333e-03,0.595867,1.523667,17.103333,0.302667,0.696667,0.500000,0.155300,0.496633,0.534667,94.426667,92.944000,77.454333,7674.100000,0.500000
13,2014,3968.000000,104.006667,105.683333,104.006667,105.690000,-1.110223e-17,3.333333e-03,0.583467,1.508333,16.810000,0.293667,0.705533,0.499867,0.153333,0.501267,0.541000,96.336667,94.799333,78.999667,7836.433333,0.500067
14,2015,3968.000000,103.006667,104.740000,103.036667,104.746667,-2.000000e-02,-2.666667e-02,0.586967,1.548333,16.810000,0.291933,0.707800,0.499933,0.150400,0.495967,0.534133,96.310000,94.715000,78.929333,7829.866667,0.499400
15,2016,3965.666667,103.906667,105.560000,103.890000,105.536667,1.000000e-02,6.666667e-03,0.582033,1.557333,16.813333,0.278767,0.721200,0.500100,0.147833,0.502500,0.541300,98.083333,96.540667,80.451333,7975.866667,0.499833
16,2017,3962.666667,106.240000,108.156667,106.210000,108.143333,1.666667e-02,2.000000e-02,0.579067,1.631667,17.006667,0.275567,0.724233,0.499900,0.142800,0.513833,0.552400,98.723333,96.962000,80.802667,8004.766667,0.499700
17,2018,3959.000000,106.173333,107.840000,106.180000,107.840000,-1.000000e-02,7.771561e-17,0.586367,1.633333,17.263333,0.267300,0.732600,0.499933,0.144633,0.521267,0.556200,99.563333,98.028667,81.690333,8085.333333,0.499767
18,2019,3963.000000,107.853333,109.720000,107.856667,109.730000,-6.666667e-03,-6.666667e-03,0.597933,1.752667,17.610000,0.271333,0.728167,0.499967,0.138933,0.524167,0.559567,102.390000,100.660333,83.883667,8310.833333,0.499867
19,2020,3413.800000,107.970000,109.983333,108.153333,110.153333,-1.800000e-01,-1.700000e-01,0.597100,1.679333,17.513333,0.267767,0.731733,0.499700,0.143333,0.528333,0.564267,102.680000,100.794667,83.995667,7169.533333,0.499067
20,2021,3476.666667,109.876667,111.713333,109.860000,111.696667,2.000000e-02,1.333333e-02,0.601833,1.802667,17.983333,0.264300,0.735667,0.500100,0.137833,0.537933,0.571800,101.420000,99.750000,83.124667,7224.900000,0.499833
21,2022,3958.333333,109.370000,111.383333,109.346667,111.360000,1.000000e-02,1.333333e-02,0.606533,1.799000,17.940000,0.274600,0.725100,0.500033,0.138567,0.531733,0.566167,100.576667,98.754333,82.295333,8143.800000,0.500100
22,2023,3965.666667,112.106667,114.076667,112.086667,114.070000,2.000000e-02,2.000000e-02,0.602933,1.803667,18.166667,0.280133,0.719033,0.499900,0.140133,0.545467,0.581500,101.553333,99.791667,83.159000,8244.433333,0.499967
23,2024,3958.333333,112.516667,114.546667,112.493333,114.516667,3.333333e-02,3.666667e-02,0.632300,1.971667,19.036667,0.283200,0.716567,0.499967,0.136500,0.546500,0.579967,100.933333,99.149667,82.624000,8176.400000,0.499967
24,2025,3957.333333,111.636667,113.680000,111.630000,113.683333,1.333333e-02,0.000000e+00,0.636667,1.869667,18.810000,0.292733,0.706533,0.499867,0.142767,0.543033,0.576200,101.400000,99.579667,82.982667,8209.633333,0.499767
25,2026,3956.666667,112.750000,114.786667,112.706667,114.733333,4.000000e-02,5.333333e-02,0.637233,1.854333,18.773333,0.304933,0.694667,0.500000,0.144100,0.545667,0.581433,102.020000,100.216667,83.513333,8260.900000,0.500400

In [14]:
conn = sqlite3.connect('nba_stats.db')

query = 'SELECT * FROM scoring_plus WHERE slug = "thompkl01"'

klay_plus_df = pd.read_sql_query(query, conn)
conn.close()
klay_plus_df

,season_end_year,slug,name,per_100_pts,true_shooting_percentage,league_avg_per_100_pts_per_player,league_avg_true_shooting_percentage,pts_plus,ts_plus,scoring_plus,team_gp,minutes_played,threshold,qualified
0,2012,thompkl01,Klay Thompson,26.1,0.545,20.699333,0.527,126.091017,103.415560,108.744292,66,1608,1207.317073,1
1,2013,thompkl01,Klay Thompson,23.1,0.533,20.952000,0.535,110.252005,99.626168,102.123240,82,2936,1500.000000,1
2,2014,thompkl01,Klay Thompson,25.5,0.555,21.136667,0.541,120.643432,102.587800,106.830874,82,2868,1500.000000,1
3,2015,thompkl01,Klay Thompson,32.5,0.591,20.948000,0.534,155.146076,110.674157,121.125058,82,2455,1500.000000,1
4,2016,thompkl01,Klay Thompson,31.4,0.597,21.112000,0.541,148.730580,110.351201,119.370355,82,2666,1500.000000,1
5,2017,thompkl01,Klay Thompson,31.2,0.592,21.631333,0.552,144.235214,107.246377,115.938754,82,2649,1500.000000,1
6,2018,thompkl01,Klay Thompson,27.6,0.598,21.568000,0.556,127.967359,107.553957,112.351106,82,2506,1500.000000,1
7,2019,thompkl01,Klay Thompson,29.7,0.571,21.944000,0.560,135.344513,101.964286,109.808639,82,2652,1500.000000,1
8,2022,thompkl01,Klay Thompson,32.8,0.547,22.276667,0.566,147.239264,96.643110,108.533206,82,941,1500.000000,0
9,2023,thompkl01,Klay Thompson,30.5,0.576,22.815333,0.581,133.682027,99.139415,107.256929,82,2279,1500.000000,1
10,2024,thompkl01,Klay Thompson,28.3,0.576,22.909333,0.580,123.530439,99.310345,105.002067,82,2284,1500.000000,1
11,2025,thompkl01,Klay Thompson,24.4,0.552,22.736000,0.576,107.318790,95.833333,98.532416,82,1965,1500.000000,1
12,2026,thompkl01,Klay Thompson,24.4,0.541,22.957333,0.581,106.284121,93.115318,96.209987,82,1497,1500.000000,0

In [15]:
conn = sqlite3.connect('nba_stats.db')

query = '''
SELECT name, scoring_plus, per_100_pts, true_shooting_percentage, pts_plus, ts_plus
FROM scoring_plus 
WHERE season_end_year = 2026
ORDER BY scoring_plus DESC
'''
scoring_plus_2026_df = pd.read_sql_query(query, conn)
conn.close()
scoring_plus_2026_df.head(25)

,name,scoring_plus,per_100_pts,true_shooting_percentage,pts_plus,ts_plus
0,Harrison Ingram,140.497178,19.3,0.917,84.068998,157.831325
1,Norchad Omier,133.687515,34.0,0.751,148.100825,129.259897
2,Giannis Antetokounmpo,133.623541,45.9,0.658,199.936113,113.253012
3,Shai Gilgeous-Alexander,132.702679,44.1,0.665,192.095481,114.457831
4,Alex Antetokounmpo,127.993119,41.3,0.651,179.898943,112.048193
5,Mark Sears,127.920886,39.3,0.666,171.187130,114.629948
6,Walker Kessler,126.933566,22.9,0.786,99.750261,135.283993
7,Luka Dončić,126.762691,44.6,0.616,194.273435,106.024096
8,Caleb Houstan,126.742460,24.9,0.769,108.462075,132.358003
9,Zyon Pullin,126.626062,23.5,0.779,102.363805,134.079174
10,Kawhi Leonard,126.529483,42.7,0.629,185.997212,108.261618
11,Nikola Jokić,126.195560,37.1,0.670,161.604135,115.318417
12,Tristen Newton,125.634627,48.0,0.581,209.083517,100.000000
13,Trentyn Flowers,125.084005,36.4,0.667,158.555001,114.802065
14,Stephen Curry,124.511925,39.7,0.637,172.929492,109.638554
15,Ty Jerome,124.305960,42.2,0.616,183.819259,106.024096
16,Jalen Duren,124.266332,32.9,0.688,143.309327,118.416523
17,Victor Wembanyama,123.575379,40.2,0.626,175.107446,107.745267
18,DaQuan Jeffries,122.455564,25.6,0.731,111.511209,125.817556
19,Riley Minix,121.723746,26.3,0.720,114.560344,123.924269
20,Joel Embiid,121.117410,40.5,0.605,176.414218,104.130809
21,Anthony Edwards,121.059624,38.9,0.617,169.444767,106.196213
22,Eric Gordon,120.979956,21.2,0.754,92.345220,129.776248
23,Cormac Ryan,120.596094,28.8,0.692,125.450110,119.104991
24,Donovan Mitchell,120.430582,38.8,0.613,169.009176,105.507745

In [16]:
conn = sqlite3.connect('nba_stats.db')

query = '''
SELECT s.name, s.season_end_year, s.slug, s.scoring_plus, s.per_100_pts, s.true_shooting_percentage, s.pts_plus, s.ts_plus
FROM scoring_plus as s
JOIN basic_stats as b ON s.slug = b.slug AND s.season_end_year = b.season_end_year
WHERE b.minutes_played > 1500
ORDER BY scoring_plus DESC
'''
scoring_plus_leaders_df = pd.read_sql_query(query, conn)
conn.close()
scoring_plus_leaders_df.head(25)

,name,season_end_year,slug,scoring_plus,per_100_pts,true_shooting_percentage,pts_plus,ts_plus
0,Stephen Curry,2016,curryst01,140.348678,41.1,0.669,194.676014,123.659889
1,James Harden,2019,hardeja01,135.767754,48.2,0.616,219.650018,110.000000
2,Kevin Durant,2014,duranke01,135.265163,40.9,0.635,193.502602,117.375231
3,Joel Embiid,2023,embiijo01,134.756972,47.1,0.655,206.440113,112.736661
4,Kevin Durant,2013,duranke01,134.238894,37.2,0.647,177.548683,120.934579
5,Stephen Curry,2018,curryst01,133.950260,37.7,0.675,174.795994,121.402878
6,Amar'e Stoudemire,2008,stoudam01,133.318311,36.5,0.656,171.850968,121.481481
7,LeBron James,2014,jamesle01,133.019945,37.1,0.649,175.524365,119.963031
8,Shai Gilgeous-Alexander,2026,gilgesh01,132.702679,44.1,0.665,192.095481,114.457831
9,LeBron James,2013,jamesle01,132.677153,36.7,0.640,175.162276,119.626168
10,Stephen Curry,2021,curryst01,132.407172,42.6,0.655,190.666587,114.510490
11,Isaiah Thomas,2017,thomais02,131.919187,41.7,0.625,192.775911,113.224638
12,Kevin Durant,2016,duranke01,131.837555,37.9,0.634,179.518757,117.190388
13,James Harden,2020,hardeja01,131.659580,43.9,0.626,199.575693,110.796460
14,Shaquille O'Neal,2003,onealsh01,131.174024,36.9,0.602,180.595403,115.992293
15,Shai Gilgeous-Alexander,2025,gilgesh01,131.113702,45.0,0.637,197.923997,110.590278
16,Joel Embiid,2021,embiijo01,130.917888,43.6,0.636,195.142329,111.188811
17,James Harden,2018,hardeja01,130.821448,41.9,0.619,194.269288,111.330935
18,Shaquille O'Neal,2002,onealsh01,130.678316,38.5,0.590,186.724421,113.461538
19,Joel Embiid,2022,embiijo01,130.518163,44.8,0.616,201.107287,108.833922
20,Nikola Jokić,2022,jokicni01,130.481809,39.0,0.661,175.071076,116.784452
21,Tracy McGrady,2003,mcgratr01,130.288414,41.0,0.564,200.661559,108.670520
22,Kevin Durant,2012,duranke01,130.100450,36.6,0.610,176.817289,115.749526
23,Giannis Antetokounmpo,2022,antetgi01,130.073086,42.2,0.633,189.435882,111.837456
24,LeBron James,2012,jamesle01,129.942295,37.1,0.605,179.232826,114.800759

In [17]:
conn = sqlite3.connect('nba_stats.db')

query = 'SELECT * FROM player_profile WHERE qualified = 1'
player_profile_df = pd.read_sql_query(query, conn)
conn.close()

player_profile_df

,player_name,team_name,team_abbreviation,team_id,season_end_year,season,slug,player_id,games_played,minutes_per_game,minutes_played,scoring_plus,pts_plus,ts_plus,per_100_pts,true_shooting_percentage,age,positions,points_per_game,fg_percentage,three_point_percentage,ft_percentage,assists_per_game,total_rebounds_per_game,turnovers_per_game,steals_per_game,blocks_per_game,per_100_reb,per_100_ast,per_100_stl,per_100_blk,per_100_tov,qualified,qualified_ast,pct_uast_fgm,uast_bin,uast_rating,profile
0,Aaron McKie,PHILADELPHIA 76ERS,PHI,1610612755,2001,2000-2001,mckieaa01,243,76,31.500000,2394,102.945609,93.052867,105.984556,18.9,0.549,28,SHOOTING GUARD,11.552632,0.473389,0.311765,0.768041,4.960526,4.092105,2.671053,1.394737,0.105263,6.7,8.1,2.3,0.2,4.4,1,1,0.447,6,1,Balanced
1,Aaron Williams,NEW JERSEY NETS,NJN,1610612751,2001,2000-2001,williaa01,1425,82,28.487805,2336,100.119872,91.083495,102.895753,18.5,0.533,29,POWER FORWARD,10.219512,0.456923,0.000000,0.787097,1.073171,7.195122,1.609756,0.719512,1.378049,13.0,1.9,1.3,2.5,2.9,1,0,0.377,5,0,Balanced
2,Al Harrington,INDIANA PACERS,IND,1610612754,2001,2000-2001,harrial01,1733,78,24.256410,1892,89.483854,79.759601,92.471042,16.2,0.479,20,POWER FORWARD,7.512821,0.443831,0.142857,0.656051,1.666667,4.884615,1.897436,0.807692,0.230769,10.5,3.6,1.7,0.5,4.1,1,0,0.328,3,-2,Finisher
3,Alan Henderson,ATLANTA HAWKS,ATL,1610612737,2001,2000-2001,hendeal01,673,73,24.794521,1810,96.797456,105.853791,94.015444,21.5,0.487,28,POWER FORWARD,10.534247,0.444113,0.000000,0.638376,0.684932,5.561644,1.726027,0.698630,0.397260,11.3,1.4,1.4,0.8,3.5,1,0,0.463,7,2,Creator
4,Allan Houston,NEW YORK KNICKS,NYK,1610612752,2001,2000-2001,houstal01,275,78,36.641026,2858,112.125466,135.886727,104.826255,27.6,0.543,29,SHOOTING GUARD,18.705128,0.448675,0.380952,0.908795,2.217949,3.628205,2.064103,0.666667,0.128205,5.4,3.3,1.0,0.2,3.1,1,1,0.507,7,2,Creator
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4860,Victor Wembanyama,SAN ANTONIO SPURS,SAS,1610612759,2026,2025-2026,wembavi01,1641705,64,29.156250,1866,123.575379,175.107446,107.745267,40.2,0.626,22,CENTER,25.000000,0.512037,0.348571,0.826667,3.109375,11.500000,2.421875,1.031250,3.078125,18.5,5.0,1.7,5.0,3.9,1,1,0.298,3,-2,Finisher
4861,Wendell Carter Jr.,ORLANDO MAGIC,ORL,1610612753,2026,2025-2026,cartewe01,1628976,78,29.333333,2288,100.791590,83.197816,106.196213,19.1,0.617,26,CENTER,11.820513,0.511774,0.318584,0.792000,1.974359,7.397436,1.282051,0.769231,0.628205,11.9,3.2,1.2,1.0,2.1,1,1,0.206,1,-4,Finisher
4862,Will Riley,WASHINGTON WIZARDS,WAS,1610612764,2026,2025-2026,rileywi01,1642860,74,22.067568,1633,94.367851,94.523173,94.320138,21.7,0.548,19,SMALL FORWARD,10.324324,0.438511,0.315789,0.800000,1.972973,2.864865,1.270270,0.729730,0.121622,6.0,4.2,1.5,0.3,2.7,1,0,0.428,6,1,Balanced
4863,Zaccharie Risacher,ATLANTA HAWKS,ATL,1610612737,2026,2025-2026,risacza01,1642258,67,22.432836,1503,93.300873,84.940179,95.869191,19.5,0.557,20,SMALL FORWARD,9.567164,0.455224,0.368217,0.644444,1.134328,3.835821,0.865672,0.880597,0.537313,7.8,2.3,1.8,1.1,1.8,1,0,0.193,1,-4,Finisher
4864,Zion Williamson,NEW ORLEANS PELICANS,NOP,1610612740,2026,2025-2026,willizi01,1629627,62,29.693548,1841,118.370509,142.873737,110.843373,32.8,0.644,25,POWER FORWARD,21.000000,0.599752,0.250000,0.716129,3.209677,5.693548,2.032258,0.967742,0.548387,8.9,5.0,1.5,0.9,3.2,1,1,0.475,7,2,Creator

In [18]:
plus_leaders_2026 = player_profile_df[player_profile_df['season_end_year'] == 2026].sort_values(by='scoring_plus', ascending=False).head(25)
plus_leaders_2026

,player_name,team_name,team_abbreviation,team_id,season_end_year,season,slug,player_id,games_played,minutes_per_game,minutes_played,scoring_plus,pts_plus,ts_plus,per_100_pts,true_shooting_percentage,age,positions,points_per_game,fg_percentage,three_point_percentage,ft_percentage,assists_per_game,total_rebounds_per_game,turnovers_per_game,steals_per_game,blocks_per_game,per_100_reb,per_100_ast,per_100_stl,per_100_blk,per_100_tov,qualified,qualified_ast,pct_uast_fgm,uast_bin,uast_rating,profile
4847,Shai Gilgeous-Alexander,OKLAHOMA CITY THUNDER,OKC,1610612760,2026,2025-2026,gilgesh01,1628983,68,33.220588,2259,132.702679,192.095481,114.457831,44.1,0.665,27,POINT GUARD,31.132353,0.553369,0.385906,0.879479,6.588235,4.294118,2.220588,1.397059,0.764706,6.1,9.3,2.0,1.1,3.1,1,1,0.803,9,4,Creator
4802,Luka Dončić,LOS ANGELES LAKERS,LAL,1610612747,2026,2025-2026,doncilu01,1629029,64,35.765625,2289,126.762691,194.273435,106.024096,44.6,0.616,26,POINT GUARD,33.484375,0.475635,0.365994,0.779845,8.281250,7.734375,3.984375,1.640625,0.531250,10.3,11.0,2.2,0.7,5.3,1,1,0.722,9,4,Creator
4788,Kawhi Leonard,LOS ANGELES CLIPPERS,LAC,1610612746,2026,2025-2026,leonaka01,202695,65,32.076923,2085,126.529483,185.997212,108.261618,42.7,0.629,34,SMALL FORWARD,27.892308,0.504769,0.386517,0.891827,3.600000,6.353846,2.046154,1.876923,0.415385,9.7,5.5,2.9,0.6,3.1,1,1,0.605,9,4,Creator
4819,Nikola Jokić,DENVER NUGGETS,DEN,1610612743,2026,2025-2026,jokicni01,203999,65,34.846154,2265,126.195560,161.604135,115.318417,37.1,0.670,30,CENTER,27.676923,0.568905,0.379661,0.831250,10.723077,12.861538,3.738462,1.415385,0.815385,17.2,14.4,1.9,1.1,5.0,1,1,0.394,5,0,Balanced
4765,Jalen Duren,DETROIT PISTONS,DET,1610612765,2026,2025-2026,durenja01,1631105,70,28.228571,1976,124.266332,143.309327,118.416523,32.9,0.688,22,CENTER,19.500000,0.650062,NaN,0.746512,1.971429,10.528571,1.857143,0.814286,0.842857,17.8,3.3,1.4,1.4,3.1,1,1,0.352,4,-1,Balanced
4860,Victor Wembanyama,SAN ANTONIO SPURS,SAS,1610612759,2026,2025-2026,wembavi01,1641705,64,29.156250,1866,123.575379,175.107446,107.745267,40.2,0.626,22,CENTER,25.000000,0.512037,0.348571,0.826667,3.109375,11.500000,2.421875,1.031250,3.078125,18.5,5.0,1.7,5.0,3.9,1,1,0.298,3,-2,Finisher
4708,Anthony Edwards,MINNESOTA TIMBERWOLVES,MIN,1610612750,2026,2025-2026,edwaran01,1630162,61,35.032787,2137,121.059624,169.444767,106.196213,38.9,0.617,24,SHOOTING GUARD,28.803279,0.489033,0.398833,0.796339,3.704918,4.950820,2.852459,1.360656,0.803279,6.7,5.0,1.8,1.1,3.8,1,1,0.610,9,4,Creator
4747,Donovan Mitchell,CLEVELAND CAVALIERS,CLE,1610612739,2026,2025-2026,mitchdo01,1628378,70,33.457143,2342,120.430582,169.009176,105.507745,38.8,0.613,29,SHOOTING GUARD,27.885714,0.483250,0.363636,0.865116,5.685714,4.514286,2.828571,1.485714,0.285714,6.3,7.9,2.1,0.4,3.9,1,1,0.615,9,4,Creator
4792,Kevin Durant,HOUSTON ROCKETS,HOU,1610612745,2026,2025-2026,duranke01,201142,78,36.410256,2840,120.022776,151.585550,110.327022,34.8,0.641,37,SMALL FORWARD,25.974359,0.520349,0.413333,0.873662,4.769231,5.461538,3.153846,0.794872,0.910256,7.3,6.4,1.1,1.2,4.2,1,1,0.461,6,1,Balanced
4864,Zion Williamson,NEW ORLEANS PELICANS,NOP,1610612740,2026,2025-2026,willizi01,1629627,62,29.693548,1841,118.370509,142.873737,110.843373,32.8,0.644,25,POWER FORWARD,21.000000,0.599752,0.250000,0.716129,3.209677,5.693548,2.032258,0.967742,0.548387,8.9,5.0,1.5,0.9,3.2,1,1,0.475,7,2,Creator
4774,Jaylen Brown,BOSTON CELTICS,BOS,1610612738,2026,2025-2026,brownja02,1627759,71,34.408451,2443,117.415804,178.592171,98.623064,41.0,0.573,29,SMALL FORWARD,28.704225,0.476993,0.346535,0.794776,5.126761,6.929577,3.647887,1.014085,0.380282,9.9,7.3,1.4,0.5,5.2,1,1,0.636,9,4,Creator
4710,Austin Reaves,LOS ANGELES LAKERS,LAL,1610612747,2026,2025-2026,reaveau01,1630559,51,34.549020,1762,117.361317,140.260193,110.327022,32.2,0.641,27,SHOOTING GUARD,23.274510,0.489501,0.359756,0.870620,5.490196,4.705882,2.960784,1.098039,0.392157,6.5,7.6,1.5,0.5,4.1,1,1,0.560,8,3,Creator
4768,Jamal Murray,DENVER NUGGETS,DEN,1610612743,2026,2025-2026,murraja01,1627750,75,35.360000,2652,117.111600,149.843187,107.056799,34.4,0.622,28,POINT GUARD,25.400000,0.483088,0.435169,0.887179,7.133333,4.400000,2.280000,0.880000,0.386667,6.0,9.7,1.2,0.5,3.1,1,1,0.575,8,3,Creator
4808,Michael Porter Jr.,BROOKLYN NETS,BKN,1610612751,2026,2025-2026,portemi01,1629008,52,32.480769,1689,115.603799,158.555001,102.409639,36.4,0.595,27,SMALL FORWARD,24.211538,0.463466,0.362887,0.859031,3.038462,7.057692,2.346154,1.057692,0.250000,10.6,4.6,1.6,0.4,3.5,1,1,0.266,3,-2,Finisher
4772,Jarrett Allen,CLEVELAND CAVALIERS,CLE,1610612739,2026,2025-2026,allenja01,1628386,56,27.125000,1519,115.213328,115.431525,115.146299,26.5,0.669,27,CENTER,15.357143,0.638258,0.100000,0.708812,1.785714,8.500000,1.339286,0.982143,0.839286,14.7,3.1,1.7,1.4,2.3,1,1,0.181,1,-4,Finisher
4742,Devin Booker,PHOENIX SUNS,PHX,1610612756,2026,2025-2026,bookede01,1626164,64,33.531250,2146,114.798922,160.732954,100.688468,36.9,0.585,29,SHOOTING GUARD,26.062500,0.455760,0.329730,0.873077,6.031250,3.875000,3.140625,0.796875,0.281250,5.5,8.5,1.1,0.4,4.5,1,1,0.597,9,4,Creator
4728,Chet Holmgren,OKLAHOMA CITY THUNDER,OKC,1610612760,2026,2025-2026,holmgch01,1631096,69,28.942029,1997,114.744436,122.400976,112.392427,28.1,0.653,23,POWER FORWARD,17.115942,0.557125,0.362140,0.792254,1.666667,8.913043,1.550725,0.623188,1.898551,14.6,2.7,1.0,3.1,2.5,1,1,0.302,3,-2,Finisher
4823,Norman Powell,MIAMI HEAT,MIA,1610612748,2026,2025-2026,powelno01,1626181,58,29.603448,1717,114.273894,145.051690,104.819277,33.3,0.609,32,SHOOTING GUARD,21.741379,0.470391,0.380488,0.827044,2.465517,3.500000,1.913793,1.103448,0.241379,5.3,3.8,1.7,0.4,2.9,1,1,0.316,4,-1,Balanced
4770,James Harden,LOS ANGELES CLIPPERS/CLEVELAND CAVALIERS,CLE,1610612739,2026,2025-2026,hardeja01,201935,70,34.828571,2438,114.200836,144.180509,104.991394,33.1,0.610,36,POINT GUARD,23.600000,0.433660,0.375218,0.883588,7.957143,4.800000,3.500000,1.128571,0.400000,6.7,11.2,1.6,0.6,4.9,1,1,0.754,9,4,Creator
4794,Keyonte George,UTAH JAZZ,UTA,1610612762,2026,2025-2026,georgke01,1641718,54,33.074074,1786,114.171530,144.616099,104.819277,33.2,0.609,22,POINT GUARD,23.611111,0.456300,0.371191,0.891534,6.148148,3.685185,3.074074,1.074074,0.259259,5.2,8.6,1.5,0.4,4.3,1,1,0.415,6,1,Balanced
4858,Tyrese Maxey,PHILADELPHIA 76ERS,PHI,1610612755,2026,2025-2026,maxeyty01,1630178,70,38.014286,2661,113.760838,154.634685,101.204819,35.5,0.588,25,POINT GUARD,28.285714,0.462358,0.367279,0.892086,6.585714,4.142857,2.442857,1.857143,0.785714,5.2,8.3,2.3,1.0,3.1,1,1,0.553,8,3,Creator
4737,Deni Avdija,PORTLAND TRAIL BLAZERS,POR,1610612757,2026,2025-2026,avdijde01,1630166,66,33.318182,2199,113.703051,147.665234,103.270224,33.9,0.600,25,SMALL FORWARD,24.212121,0.462406,0.318066,0.801639,6.696970,6.878788,3.833333,0.772727,0.621212,9.6,9.4,1.1,0.9,5.4,1,1,0.508,7,2,Creator
4764,Jalen Brunson,NEW YORK KNICKS,NYK,1610612752,2026,2025-2026,brunsja01,1628973,74,35.000000,2590,113.526392,158.119410,99.827883,36.3,0.580,29,POINT GUARD,26.040541,0.467119,0.369318,0.840855,6.797297,3.337838,2.364865,0.770270,0.108108,4.6,9.5,1.1,0.2,3.3,1,1,0.689,9,4,Creator
4787,Karl-Anthony Towns,NEW YORK KNICKS,NYK,1610612752,2026,2025-2026,townska01,1626157,75,30.960000,2322,113.338586,135.468696,106.540448,31.1,0.619,30,CENTER,20.053333,0.500969,0.368078,0.858173,3.013333,11.853333,2.493333,0.866667,0.533333,18.4,4.7,1.3,0.8,3.9,1,1,0.342,4,-1,Balanced
4795,Kon Knueppel,CHARLOTTE HORNETS,CHA,1610612766,2026,2025-2026,knuepko01,1642851,81,31.493827,2551,112.315773,123.272157,108.950086,28.3,0.633,20,SMALL FORWARD,18.493827,0.475092,0.425234,0.862832,3.382716,5.333333,1.987654,0.703704,0.234568,8.2,5.2,1.1,0.4,3.0,1,1,0.233,2,-3,Finisher

In [19]:
ppg_leaders_2026 = player_profile_df[player_profile_df['season_end_year'] == 2026].sort_values(by='points_per_game', ascending=False).head(25)
ppg_leaders_2026

,player_name,team_name,team_abbreviation,team_id,season_end_year,season,slug,player_id,games_played,minutes_per_game,minutes_played,scoring_plus,pts_plus,ts_plus,per_100_pts,true_shooting_percentage,age,positions,points_per_game,fg_percentage,three_point_percentage,ft_percentage,assists_per_game,total_rebounds_per_game,turnovers_per_game,steals_per_game,blocks_per_game,per_100_reb,per_100_ast,per_100_stl,per_100_blk,per_100_tov,qualified,qualified_ast,pct_uast_fgm,uast_bin,uast_rating,profile
4802,Luka Dončić,LOS ANGELES LAKERS,LAL,1610612747,2026,2025-2026,doncilu01,1629029,64,35.765625,2289,126.762691,194.273435,106.024096,44.6,0.616,26,POINT GUARD,33.484375,0.475635,0.365994,0.779845,8.281250,7.734375,3.984375,1.640625,0.531250,10.3,11.0,2.2,0.7,5.3,1,1,0.722,9,4,Creator
4847,Shai Gilgeous-Alexander,OKLAHOMA CITY THUNDER,OKC,1610612760,2026,2025-2026,gilgesh01,1628983,68,33.220588,2259,132.702679,192.095481,114.457831,44.1,0.665,27,POINT GUARD,31.132353,0.553369,0.385906,0.879479,6.588235,4.294118,2.220588,1.397059,0.764706,6.1,9.3,2.0,1.1,3.1,1,1,0.803,9,4,Creator
4708,Anthony Edwards,MINNESOTA TIMBERWOLVES,MIN,1610612750,2026,2025-2026,edwaran01,1630162,61,35.032787,2137,121.059624,169.444767,106.196213,38.9,0.617,24,SHOOTING GUARD,28.803279,0.489033,0.398833,0.796339,3.704918,4.950820,2.852459,1.360656,0.803279,6.7,5.0,1.8,1.1,3.8,1,1,0.610,9,4,Creator
4774,Jaylen Brown,BOSTON CELTICS,BOS,1610612738,2026,2025-2026,brownja02,1627759,71,34.408451,2443,117.415804,178.592171,98.623064,41.0,0.573,29,SMALL FORWARD,28.704225,0.476993,0.346535,0.794776,5.126761,6.929577,3.647887,1.014085,0.380282,9.9,7.3,1.4,0.5,5.2,1,1,0.636,9,4,Creator
4858,Tyrese Maxey,PHILADELPHIA 76ERS,PHI,1610612755,2026,2025-2026,maxeyty01,1630178,70,38.014286,2661,113.760838,154.634685,101.204819,35.5,0.588,25,POINT GUARD,28.285714,0.462358,0.367279,0.892086,6.585714,4.142857,2.442857,1.857143,0.785714,5.2,8.3,2.3,1.0,3.1,1,1,0.553,8,3,Creator
4788,Kawhi Leonard,LOS ANGELES CLIPPERS,LAC,1610612746,2026,2025-2026,leonaka01,202695,65,32.076923,2085,126.529483,185.997212,108.261618,42.7,0.629,34,SMALL FORWARD,27.892308,0.504769,0.386517,0.891827,3.600000,6.353846,2.046154,1.876923,0.415385,9.7,5.5,2.9,0.6,3.1,1,1,0.605,9,4,Creator
4747,Donovan Mitchell,CLEVELAND CAVALIERS,CLE,1610612739,2026,2025-2026,mitchdo01,1628378,70,33.457143,2342,120.430582,169.009176,105.507745,38.8,0.613,29,SHOOTING GUARD,27.885714,0.483250,0.363636,0.865116,5.685714,4.514286,2.828571,1.485714,0.285714,6.3,7.9,2.1,0.4,3.9,1,1,0.615,9,4,Creator
4819,Nikola Jokić,DENVER NUGGETS,DEN,1610612743,2026,2025-2026,jokicni01,203999,65,34.846154,2265,126.195560,161.604135,115.318417,37.1,0.670,30,CENTER,27.676923,0.568905,0.379661,0.831250,10.723077,12.861538,3.738462,1.415385,0.815385,17.2,14.4,1.9,1.1,5.0,1,1,0.394,5,0,Balanced
4742,Devin Booker,PHOENIX SUNS,PHX,1610612756,2026,2025-2026,bookede01,1626164,64,33.531250,2146,114.798922,160.732954,100.688468,36.9,0.585,29,SHOOTING GUARD,26.062500,0.455760,0.329730,0.873077,6.031250,3.875000,3.140625,0.796875,0.281250,5.5,8.5,1.1,0.4,4.5,1,1,0.597,9,4,Creator
4764,Jalen Brunson,NEW YORK KNICKS,NYK,1610612752,2026,2025-2026,brunsja01,1628973,74,35.000000,2590,113.526392,158.119410,99.827883,36.3,0.580,29,POINT GUARD,26.040541,0.467119,0.369318,0.840855,6.797297,3.337838,2.364865,0.770270,0.108108,4.6,9.5,1.1,0.2,3.3,1,1,0.689,9,4,Creator
4792,Kevin Durant,HOUSTON ROCKETS,HOU,1610612745,2026,2025-2026,duranke01,201142,78,36.410256,2840,120.022776,151.585550,110.327022,34.8,0.641,37,SMALL FORWARD,25.974359,0.520349,0.413333,0.873662,4.769231,5.461538,3.153846,0.794872,0.910256,7.3,6.4,1.1,1.2,4.2,1,1,0.461,6,1,Balanced
4768,Jamal Murray,DENVER NUGGETS,DEN,1610612743,2026,2025-2026,murraja01,1627750,75,35.360000,2652,117.111600,149.843187,107.056799,34.4,0.622,28,POINT GUARD,25.400000,0.483088,0.435169,0.887179,7.133333,4.400000,2.280000,0.880000,0.386667,6.0,9.7,1.2,0.5,3.1,1,1,0.575,8,3,Creator
4860,Victor Wembanyama,SAN ANTONIO SPURS,SAS,1610612759,2026,2025-2026,wembavi01,1641705,64,29.156250,1866,123.575379,175.107446,107.745267,40.2,0.626,22,CENTER,25.000000,0.512037,0.348571,0.826667,3.109375,11.500000,2.421875,1.031250,3.078125,18.5,5.0,1.7,5.0,3.9,1,1,0.298,3,-2,Finisher
4737,Deni Avdija,PORTLAND TRAIL BLAZERS,POR,1610612757,2026,2025-2026,avdijde01,1630166,66,33.318182,2199,113.703051,147.665234,103.270224,33.9,0.600,25,SMALL FORWARD,24.212121,0.462406,0.318066,0.801639,6.696970,6.878788,3.833333,0.772727,0.621212,9.6,9.4,1.1,0.9,5.4,1,1,0.508,7,2,Creator
4808,Michael Porter Jr.,BROOKLYN NETS,BKN,1610612751,2026,2025-2026,portemi01,1629008,52,32.480769,1689,115.603799,158.555001,102.409639,36.4,0.595,27,SMALL FORWARD,24.211538,0.463466,0.362887,0.859031,3.038462,7.057692,2.346154,1.057692,0.250000,10.6,4.6,1.6,0.4,3.5,1,1,0.266,3,-2,Finisher
4829,Pascal Siakam,INDIANA PACERS,IND,1610612754,2026,2025-2026,siakapa01,1627783,62,33.177419,2057,108.392517,146.358462,96.729776,33.6,0.562,31,POWER FORWARD,23.951613,0.483983,0.358362,0.693122,3.806452,6.629032,2.225806,1.112903,0.403226,9.3,5.3,1.6,0.6,3.1,1,1,0.447,6,1,Balanced
4723,Cade Cunningham,DETROIT PISTONS,DET,1610612765,2026,2025-2026,cunnica01,1630595,64,33.937500,2172,108.553493,145.922871,97.074010,33.5,0.564,24,POINT GUARD,23.921875,0.460892,0.341530,0.811518,9.906250,5.546875,3.687500,1.437500,0.843750,7.8,13.9,2.0,1.2,5.2,1,1,0.664,9,4,Creator
4794,Keyonte George,UTAH JAZZ,UTA,1610612762,2026,2025-2026,georgke01,1641718,54,33.074074,1786,114.171530,144.616099,104.819277,33.2,0.609,22,POINT GUARD,23.611111,0.456300,0.371191,0.891534,6.148148,3.685185,3.074074,1.074074,0.259259,5.2,8.6,1.5,0.4,4.3,1,1,0.415,6,1,Balanced
4770,James Harden,LOS ANGELES CLIPPERS/CLEVELAND CAVALIERS,CLE,1610612739,2026,2025-2026,hardeja01,201935,70,34.828571,2438,114.200836,144.180509,104.991394,33.1,0.610,36,POINT GUARD,23.600000,0.433660,0.375218,0.883588,7.957143,4.800000,3.500000,1.128571,0.400000,6.7,11.2,1.6,0.6,4.9,1,1,0.754,9,4,Creator
4710,Austin Reaves,LOS ANGELES LAKERS,LAL,1610612747,2026,2025-2026,reaveau01,1630559,51,34.549020,1762,117.361317,140.260193,110.327022,32.2,0.641,27,SHOOTING GUARD,23.274510,0.489501,0.359756,0.870620,5.490196,4.705882,2.960784,1.098039,0.392157,6.5,7.6,1.5,0.5,4.1,1,1,0.560,8,3,Creator
4766,Jalen Johnson,ATLANTA HAWKS,ATL,1610612737,2026,2025-2026,johnsja05,1630552,72,35.166667,2532,106.799686,128.934836,100.000000,29.6,0.581,24,SMALL FORWARD,22.513889,0.488599,0.351906,0.787958,7.861111,10.277778,3.388889,1.236111,0.430556,13.5,10.4,1.6,0.6,4.5,1,1,0.450,6,1,Balanced
4828,Paolo Banchero,ORLANDO MAGIC,ORL,1610612753,2026,2025-2026,banchpa01,1631094,72,34.750000,2502,105.643554,132.419561,97.418244,30.4,0.566,23,POWER FORWARD,22.208333,0.459201,0.305455,0.774576,5.180556,8.388889,3.083333,0.708333,0.555556,11.5,7.1,1.0,0.8,4.2,1,1,0.505,7,2,Creator
4823,Norman Powell,MIAMI HEAT,MIA,1610612748,2026,2025-2026,powelno01,1626181,58,29.603448,1717,114.273894,145.051690,104.819277,33.3,0.609,32,SHOOTING GUARD,21.741379,0.470391,0.380488,0.827044,2.465517,3.500000,1.913793,1.103448,0.241379,5.3,3.8,1.7,0.4,2.9,1,1,0.316,4,-1,Balanced
4856,Trey Murphy III,NEW ORLEANS PELICANS,NOP,1610612740,2026,2025-2026,murphtr02,1630530,66,35.469697,2341,109.989473,124.578929,105.507745,28.6,0.613,25,SMALL FORWARD,21.515152,0.470476,0.378761,0.886179,3.787879,5.712121,1.818182,1.500000,0.363636,7.6,5.0,2.0,0.5,2.4,1,1,0.231,2,-3,Finisher
4716,Brandon Ingram,TORONTO RAPTORS,TOR,1610612761,2026,2025-2026,ingrabr01,1627742,77,33.818182,2604,107.077060,134.597514,98.623064,30.9,0.573,28,SMALL FORWARD,21.493506,0.476708,0.382436,0.820225,3.688312,5.584416,2.428571,0.753247,0.714286,8.0,5.3,1.1,1.0,3.5,1,1,0.464,7,2,Creator

In [20]:
conn = sqlite3.connect('nba_stats.db')

query = 'SELECT * FROM scoring_splits'
scoring_splits_df = pd.read_sql_query(query, conn)

conn.close()

scoring_splits_df

,season_end_year,player_id,player_name,nickname,team_id,team_abbreviation,age,gp,w,l,w_pct,min,pct_fga_2pt,pct_fga_3pt,pct_pts_2pt,pct_pts_2pt_mr,pct_pts_3pt,pct_pts_fb,pct_pts_ft,pct_pts_off_tov,pct_pts_paint,pct_ast_2pm,pct_uast_2pm,pct_ast_3pm,pct_uast_3pm,pct_ast_fgm,pct_uast_fgm,fgm,fga,fg_pct,gp_rank,w_rank,l_rank,w_pct_rank,min_rank,pct_fga_2pt_rank,pct_fga_3pt_rank,pct_pts_2pt_rank,pct_pts_2pt_mr_rank,pct_pts_3pt_rank,pct_pts_fb_rank,pct_pts_ft_rank,pct_pts_off_tov_rank,pct_pts_paint_rank,pct_ast_2pm_rank,pct_uast_2pm_rank,pct_ast_3pm_rank,pct_uast_3pm_rank,pct_ast_fgm_rank,pct_uast_fgm_rank,fgm_rank,fga_rank,fg_pct_rank,team_count,slug
0,2001,920,A.C. Green,A.C.,1610612748,MIA,37.0,82,50,32,0.610,17.2,0.981,0.019,0.785,0.436,0.000,0.106,0.215,0.199,0.349,0.764,0.236,0.000,0.000,0.764,0.236,144,324,0.444,2,38,262,130,253,146,294,113,50,295,256,153,129,265,52,383,279,208,74,361,213,216,171,1,greenac01
1,2001,2062,A.J. Guyton,A.J.,1610612741,CHI,23.0,33,6,27,0.182,19.0,0.641,0.359,0.515,0.374,0.409,0.035,0.076,0.207,0.141,0.608,0.392,0.852,0.148,0.692,0.308,78,192,0.406,334,381,204,419,228,377,63,355,81,45,384,405,102,409,232,203,189,105,151,283,291,285,293,1,guytoaj01
2,2001,243,Aaron McKie,Aaron,1610612755,PHI,28.0,76,51,25,0.671,31.5,0.762,0.238,0.649,0.269,0.181,0.183,0.170,0.177,0.380,0.481,0.519,0.943,0.057,0.553,0.447,338,714,0.473,120,31,178,57,89,305,135,268,166,155,99,261,192,236,326,109,124,171,316,119,80,92,106,1,mckieaa01
3,2001,1425,Aaron Williams,Aaron,1610612751,NJN,29.0,82,26,56,0.317,28.5,0.997,0.003,0.709,0.105,0.000,0.060,0.291,0.169,0.604,0.623,0.377,0.000,0.000,0.623,0.377,297,650,0.457,2,223,427,358,115,89,351,214,363,295,342,32,216,81,212,223,279,208,258,177,105,109,141,1,williaa01
4,2001,228,Adam Keefe,Adam,1610612744,GSW,31.0,67,14,53,0.209,12.6,0.981,0.019,0.750,0.226,0.018,0.131,0.232,0.250,0.524,0.683,0.317,1.000,0.000,0.688,0.313,64,159,0.403,192,318,420,407,317,148,291,157,223,262,202,114,29,120,128,307,1,208,159,275,306,300,300,1,keefead01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12805,2026,203897,Zach LaVine,Zach,1610612758,SAC,31.0,39,9,30,0.231,31.4,0.536,0.464,0.436,0.107,0.397,0.183,0.167,0.143,0.329,0.577,0.423,0.768,0.232,0.649,0.351,262,547,0.479,368,432,395,507,59,321,262,361,75,242,135,214,346,408,310,265,429,88,358,220,149,156,216,1,lavinza01
12806,2026,1630192,Zeke Nnaji,Zeke,1610612743,DEN,25.0,52,38,14,0.731,12.0,0.642,0.358,0.600,0.032,0.221,0.111,0.179,0.158,0.568,0.789,0.211,1.000,0.000,0.831,0.169,71,151,0.470,286,128,175,66,442,203,380,147,302,423,357,181,266,154,69,506,1,368,112,466,377,385,246,1,nnajize01
12807,2026,1630533,Ziaire Williams,Ziaire,1610612751,BKN,24.0,56,13,43,0.232,22.9,0.420,0.580,0.342,0.021,0.450,0.190,0.208,0.253,0.321,0.643,0.357,0.977,0.023,0.799,0.201,184,433,0.425,247,384,527,505,224,443,140,458,362,192,112,106,37,421,241,334,182,335,161,417,231,216,400,1,willizi02
12808,2026,1629627,Zion Williamson,Zion,1610612740,NOP,25.0,62,22,40,0.355,29.7,0.995,0.005,0.742,0.009,0.002,0.119,0.256,0.146,0.733,0.524,0.476,1.000,0.000,0.525,0.475,484,807,0.600,201,277,508,407,96,39,544,81,430,516,328,50,333,70,359,215,1,368,471,107,39,71,56,1,willizi01
12809,2026,1642389,Zyon Pullin,Zyon,1610612750,MIN,25.0,5,4,1,0.800,8.5,0.769,0.231,0.696,0.000,0.130,0.261,0.174,0.087,0.696,0.250,0.750,1.000,0.000,0.333,0.667,9,13,0.692,539,487,4,20,507,113,469,101,460,464,34,198,531,88,543,27,1,368,559,16,518,533,13,1,pullizy01

In [21]:
conn = sqlite3.connect('nba_stats.db')

query = 'SELECT * FROM scoring_profile'
scoring_profile_df = pd.read_sql_query(query, conn)
conn.close()

scoring_profile_df

,season_end_year,slug,player_id,player_name,team_id,team_abbreviation,team_name,age,gp,team_gp,pct_uast_fgm,made_field_goals,threshold,qualified,uast_bin,uast_rating,profile
0,2001,greenac01,920,A.C. Green,1610612748,MIA,Miami Heat,37.0,82,82,0.236,144,300.0,0,1,-4,Finisher
1,2001,guytoaj01,2062,A.J. Guyton,1610612741,CHI,Chicago Bulls,23.0,33,82,0.308,78,300.0,0,2,-3,Finisher
2,2001,mckieaa01,243,Aaron McKie,1610612755,PHI,Philadelphia 76ers,28.0,76,82,0.447,338,300.0,1,6,1,Balanced
3,2001,williaa01,1425,Aaron Williams,1610612751,NJN,New Jersey Nets,29.0,82,82,0.377,297,300.0,0,5,0,Balanced
4,2001,keefead01,228,Adam Keefe,1610612744,GSW,Golden State Warriors,31.0,67,82,0.313,64,300.0,0,3,-2,Finisher
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12797,2026,lavinza01,203897,Zach LaVine,1610612758,SAC,Sacramento Kings,31.0,39,82,0.351,262,300.0,0,4,-1,Balanced
12798,2026,nnajize01,1630192,Zeke Nnaji,1610612743,DEN,Denver Nuggets,25.0,52,82,0.169,71,300.0,0,1,-4,Finisher
12799,2026,willizi02,1630533,Ziaire Williams,1610612751,BKN,Brooklyn Nets,24.0,56,82,0.201,184,300.0,0,1,-4,Finisher
12800,2026,willizi01,1629627,Zion Williamson,1610612740,NOP,New Orleans Pelicans,25.0,62,82,0.475,484,300.0,1,7,2,Creator
12801,2026,pullizy01,1642389,Zyon Pullin,1610612750,MIN,Minnesota Timberwolves,25.0,5,82,0.667,9,300.0,0,9,4,Creator

In [22]:
conn = sqlite3.connect('nba_stats.db')

query = 'SELECT * FROM player_profile'
player_profile_df = pd.read_sql_query(query, conn)
conn.close()

player_profile_df

,player_name,team_name,team_abbreviation,team_id,season_end_year,season,slug,player_id,games_played,minutes_per_game,minutes_played,scoring_plus,pts_plus,ts_plus,per_100_pts,true_shooting_percentage,age,positions,points_per_game,fg_percentage,three_point_percentage,ft_percentage,assists_per_game,total_rebounds_per_game,turnovers_per_game,steals_per_game,blocks_per_game,per_100_reb,per_100_ast,per_100_stl,per_100_blk,per_100_tov,qualified,qualified_ast,pct_uast_fgm,uast_bin,uast_rating,profile
0,A.C. Green,MIAMI HEAT,MIA,1610612748,2001,2000-2001,greenac01,920,82,17.207317,1411,88.626922,67.943364,94.980695,13.8,0.492,37,POWER FORWARD,4.475610,0.444444,0.000000,0.711712,0.475610,3.817073,0.548780,0.365854,0.097561,11.8,1.5,1.1,0.3,1.7,0,0,0.236,1,-4,Finisher
1,A.J. Guyton,CHICAGO BULLS,CHI,1610612741,2001,2000-2001,guytoaj01,2062,33,19.090909,630,92.656693,83.206003,95.559846,16.9,0.495,22,POINT GUARD,6.000000,0.406250,0.391304,0.833333,1.939394,1.090909,0.727273,0.272727,0.151515,3.1,5.5,0.8,0.4,2.0,0,0,0.308,2,-3,Finisher
2,Aaron McKie,PHILADELPHIA 76ERS,PHI,1610612755,2001,2000-2001,mckieaa01,243,76,31.500000,2394,102.945609,93.052867,105.984556,18.9,0.549,28,SHOOTING GUARD,11.552632,0.473389,0.311765,0.768041,4.960526,4.092105,2.671053,1.394737,0.105263,6.7,8.1,2.3,0.2,4.4,1,1,0.447,6,1,Balanced
3,Aaron Williams,NEW JERSEY NETS,NJN,1610612751,2001,2000-2001,williaa01,1425,82,28.487805,2336,100.119872,91.083495,102.895753,18.5,0.533,29,POWER FORWARD,10.219512,0.456923,0.000000,0.787097,1.073171,7.195122,1.609756,0.719512,1.378049,13.0,1.9,1.3,2.5,2.9,1,0,0.377,5,0,Balanced
4,Adam Keefe,GOLDEN STATE WARRIORS,GSW,1610612744,2001,2000-2001,keefead01,228,67,12.477612,836,78.143295,49.726665,86.872587,10.1,0.450,30,POWER FORWARD,2.507463,0.402516,0.333333,0.619048,0.537313,3.119403,0.597015,0.417910,0.298507,12.5,2.2,1.7,1.2,2.4,0,0,0.313,3,-2,Finisher
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12797,Zach LaVine,SACRAMENTO KINGS,SAC,1610612758,2026,2025-2026,lavinza01,203897,39,31.384615,1224,110.632962,126.756882,105.679862,29.1,0.614,30,SHOOTING GUARD,19.179487,0.478976,0.389764,0.880282,2.282051,2.769231,1.897436,0.717949,0.256410,4.2,3.5,1.1,0.4,2.9,0,0,0.351,4,-1,Balanced
12798,Zeke Nnaji,DENVER NUGGETS,DEN,1610612743,2026,2025-2026,nnajize01,1630192,52,12.038462,626,88.621444,64.467418,96.041308,14.8,0.558,25,POWER FORWARD,3.653846,0.470199,0.259259,0.772727,0.557692,2.615385,0.519231,0.326923,0.461538,10.6,2.3,1.3,1.9,2.1,0,0,0.169,1,-4,Finisher
12799,Ziaire Williams,BROOKLYN NETS,BKN,1610612751,2026,2025-2026,willizi02,1630533,56,22.875000,1281,98.142515,93.216401,99.655766,21.4,0.579,24,SMALL FORWARD,10.232143,0.424942,0.342629,0.850000,1.071429,2.392857,1.053571,1.357143,0.375000,5.0,2.2,2.8,0.8,2.2,0,0,0.201,1,-4,Finisher
12800,Zion Williamson,NEW ORLEANS PELICANS,NOP,1610612740,2026,2025-2026,willizi01,1629627,62,29.693548,1841,118.370509,142.873737,110.843373,32.8,0.644,25,POWER FORWARD,21.000000,0.599752,0.250000,0.716129,3.209677,5.693548,2.032258,0.967742,0.548387,8.9,5.0,1.5,0.9,3.2,1,1,0.475,7,2,Creator
12801,Zyon Pullin,MINNESOTA TIMBERWOLVES,MIN,1610612750,2026,2025-2026,pullizy01,1642389,5,8.600000,43,126.626062,102.363805,134.079174,23.5,0.779,24,SHOOTING GUARD,4.600000,0.692308,0.333333,1.000000,1.800000,0.600000,0.600000,0.200000,0.000000,3.1,9.2,1.0,0.0,3.1,0,0,0.667,9,4,Creator

In [23]:
conn = sqlite3.connect('nba_stats.db')

query = 'SELECT * FROM team_advanced_stats'
team_advanced_stats_df = pd.read_sql_query(query, conn)
conn.close()

team_advanced_stats_df

,season_end_year,team_id,team_name,gp,w,l,w_pct,min,e_off_rating,off_rating,e_def_rating,def_rating,e_net_rating,net_rating,ast_pct,ast_to,ast_ratio,oreb_pct,dreb_pct,reb_pct,tm_tov_pct,efg_pct,ts_pct,e_pace,pace,pace_per40,poss,pie,gp_rank,w_rank,l_rank,w_pct_rank,min_rank,off_rating_rank,def_rating_rank,net_rating_rank,ast_pct_rank,ast_to_rank,ast_ratio_rank,oreb_pct_rank,dreb_pct_rank,reb_pct_rank,tm_tov_pct_rank,efg_pct_rank,ts_pct_rank,pace_rank,pie_rank
0,2001,1610612737,Atlanta Hawks,82,25,57,0.305,3946.0,95.6,96.9,101.9,102.4,-6.3,-5.5,0.542,1.14,14.9,0.313,0.691,0.501,0.178,0.456,0.500,94.5,93.63,78.02,7695,0.452,1,25,25,25,27,27,17,25,29,29,29,15,12,14,28,25,26,11,26
1,2001,1610612738,Boston Celtics,82,36,46,0.439,3966.0,99.0,100.1,100.9,102.3,-1.9,-2.2,0.616,1.33,16.2,0.280,0.690,0.478,0.166,0.473,0.521,95.0,93.81,78.17,7748,0.468,1,20,20,20,13,17,15,20,12,21,19,26,15,28,20,14,12,10,23
2,2001,1610612766,Charlotte Hornets,82,46,36,0.561,3976.0,99.3,99.7,96.3,97.6,3.0,2.1,0.679,1.61,17.8,0.315,0.710,0.513,0.156,0.457,0.506,92.0,91.24,76.04,7565,0.527,1,14,14,14,8,19,6,14,2,6,7,14,1,6,10,24,23,21,7
3,2001,1610612741,Chicago Bulls,82,15,67,0.183,3971.0,94.3,95.9,104.9,105.9,-10.6,-10.0,0.665,1.40,17.4,0.302,0.673,0.480,0.173,0.450,0.495,91.7,90.47,75.39,7486,0.432,1,29,29,29,10,29,28,29,3,18,9,20,27,27,25,28,28,27,28
4,2001,1610612739,Cleveland Cavaliers,82,30,52,0.366,3966.0,97.4,99.3,102.0,103.5,-4.6,-4.2,0.591,1.27,16.2,0.331,0.678,0.505,0.177,0.459,0.509,93.9,92.32,76.94,7613,0.469,1,23,23,23,17,22,21,23,20,25,20,7,23,10,27,23,22,17,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,2026,1610612758,Sacramento Kings,82,22,60,0.268,3951.0,109.0,110.6,118.0,120.3,-9.0,-9.7,0.615,1.78,18.2,0.298,0.685,0.487,0.143,0.525,0.560,101.8,100.12,83.43,8233,0.455,1,26,26,26,14,26,28,28,20,19,21,17,23,25,15,29,29,17,28
772,2026,1610612759,San Antonio Spurs,82,62,20,0.756,3946.0,116.6,118.7,108.5,110.4,8.1,8.4,0.646,2.09,19.5,0.306,0.724,0.521,0.133,0.559,0.595,102.5,100.72,83.93,8275,0.542,1,2,2,2,26,3,3,3,13,5,7,10,1,6,5,7,5,12,3
773,2026,1610612761,Toronto Raptors,82,46,36,0.561,3956.0,113.0,115.0,110.0,112.1,2.9,2.9,0.692,2.16,20.5,0.300,0.693,0.496,0.137,0.546,0.581,101.0,99.22,82.68,8177,0.522,1,11,11,11,13,15,5,11,3,2,1,16,16,15,7,16,15,21,8
774,2026,1610612762,Utah Jazz,82,22,60,0.268,3966.0,111.2,112.7,119.3,120.8,-8.0,-8.2,0.696,1.91,19.9,0.298,0.693,0.492,0.149,0.536,0.575,104.9,103.54,86.28,8558,0.464,1,26,26,26,6,22,29,27,2,10,5,18,17,19,22,20,20,2,27
775,2026,1610612764,Washington Wizards,82,17,65,0.207,3951.0,108.2,109.7,119.6,121.5,-11.4,-11.8,0.599,1.60,17.6,0.285,0.664,0.471,0.152,0.535,0.566,104.0,102.49,85.41,8442,0.433,1,30,30,30,25,29,30,30,24,28,27,23,29,30,24,21,27,6,30

In [24]:
conn = sqlite3.connect('nba_stats.db')

query = 'SELECT * FROM team_per_game_stats'
team_per_game_stats_df = pd.read_sql_query(query, conn)
conn.close()

team_per_game_stats_df

,season_end_year,team_id,team_name,gp,w,l,w_pct,per_game_min,per_game_fgm,per_game_fga,per_game_fg_pct,per_game_fg3m,per_game_fg3a,per_game_fg3_pct,per_game_ftm,per_game_fta,per_game_ft_pct,per_game_oreb,per_game_dreb,per_game_reb,per_game_ast,per_game_tov,per_game_stl,per_game_blk,per_game_blka,per_game_pf,per_game_pfd,per_game_pts,per_game_plus_minus,gp_rank,w_rank,l_rank,w_pct_rank,min_rank,fgm_rank,fga_rank,fg_pct_rank,fg3m_rank,fg3a_rank,fg3_pct_rank,ftm_rank,fta_rank,ft_pct_rank,oreb_rank,dreb_rank,reb_rank,ast_rank,tov_rank,stl_rank,blk_rank,blka_rank,pf_rank,pfd_rank,pts_rank,plus_minus_rank
0,2001,1610612737,Atlanta Hawks,82,25,57,0.305,48.1,35.1,81.3,0.431,4.1,11.4,0.357,16.8,22.1,0.759,12.5,30.4,42.9,19.0,16.7,7.7,4.7,6.3,22.7,0.1,91.0,-5.2,1,25,25,25,27,20,12,22,20,24,11,27,27,13,9,16,12,28,28,16,21,27,14,8,26,25
1,2001,1610612738,Boston Celtics,82,36,46,0.439,48.4,33.8,79.1,0.428,7.2,19.9,0.363,19.8,26.7,0.740,10.9,28.9,39.8,20.8,15.7,9.4,4.1,5.4,23.8,0.0,94.6,-2.1,1,20,20,20,13,26,20,25,1,1,8,6,7,20,25,27,26,19,19,3,28,17,25,22,16,20
2,2001,1610612766,Charlotte Hornets,82,46,36,0.561,48.5,34.1,79.3,0.431,4.1,12.0,0.346,19.5,26.2,0.745,12.6,31.8,44.4,23.2,14.4,8.1,5.5,4.6,21.4,0.1,91.9,2.1,1,14,14,14,8,24,17,23,19,20,18,9,8,19,8,4,7,7,8,11,11,6,11,18,24,14
3,2001,1610612741,Chicago Bulls,82,15,67,0.183,48.4,33.2,78.2,0.424,4.0,11.6,0.346,17.2,23.3,0.739,11.3,27.6,38.9,22.1,15.8,8.2,4.6,5.2,23.2,0.0,87.6,-9.1,1,29,29,29,10,28,25,27,22,22,17,26,22,21,20,29,29,12,21,7,24,14,19,22,29,29
4,2001,1610612739,Cleveland Cavaliers,82,30,52,0.366,48.4,35.2,79.7,0.442,2.7,8.0,0.334,19.0,24.9,0.765,12.4,29.8,42.1,20.8,16.5,7.8,5.3,6.6,23.2,0.1,92.2,-4.2,1,23,23,23,17,18,16,14,29,29,24,12,14,8,11,20,17,19,27,15,13,29,20,6,22,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,2026,1610612758,Sacramento Kings,82,22,60,0.268,48.2,41.6,89.0,0.467,10.3,30.2,0.340,17.6,22.8,0.772,11.5,30.8,42.3,25.5,14.3,8.0,4.5,4.7,19.7,18.3,111.0,-10.0,1,26,26,26,14,20,20,18,30,30,29,21,19,21,13,28,22,20,13,20,20,14,15,28,28,29
772,2026,1610612759,San Antonio Spurs,82,62,20,0.756,48.1,43.4,89.9,0.483,13.6,37.9,0.359,19.3,24.6,0.787,11.4,35.6,47.0,28.1,13.5,7.5,5.5,4.6,18.9,20.2,119.8,8.3,1,2,2,2,26,4,13,6,16,14,15,11,13,12,14,1,2,9,4,25,8,11,4,12,3,2
773,2026,1610612761,Toronto Raptors,82,46,36,0.561,48.2,42.6,88.4,0.482,11.4,32.1,0.354,18.0,23.4,0.769,10.9,31.2,42.1,29.5,13.7,8.8,4.8,5.0,20.9,19.8,114.6,2.8,1,11,11,11,13,10,24,7,26,26,21,17,15,22,21,23,24,3,8,11,15,19,23,19,21,11
774,2026,1610612762,Utah Jazz,82,22,60,0.268,48.4,42.5,91.1,0.467,12.6,36.7,0.345,19.9,25.3,0.786,12.0,31.8,43.8,29.6,15.5,8.9,3.8,5.8,21.1,20.3,117.6,-8.4,1,26,26,26,6,12,3,17,20,18,25,8,8,13,9,20,16,2,26,8,30,30,27,10,9,27
775,2026,1610612764,Washington Wizards,82,17,65,0.207,48.2,41.8,90.4,0.463,13.0,36.4,0.359,16.2,21.2,0.766,11.0,30.9,41.9,25.0,15.7,8.0,5.5,5.4,21.3,17.9,112.9,-12.0,1,30,30,30,25,18,7,22,19,19,16,27,26,23,18,27,26,25,27,21,5,25,29,29,25,30